openapi: 3.0.3
info:
  title: Fatture in Cloud API v2 - API Reference
  description: >-
    Connect your software with Fatture in Cloud, the invoicing platform chosen
    by more than 400.000 businesses in Italy. 


    The Fatture in Cloud API is based on REST, and makes possible to interact
    with the user related data prior authorization via OAuth2 protocol.
  contact:
    name: Fatture in Cloud
    url: https://www.fattureincloud.it
    email: info@fattureincloud.it
  license:
    name: MIT
    url: >-
      https://github.com/fattureincloud/openapi-fattureincloud/blob/master/LICENSE
  version: 2.0.9
servers:
  - url: https://api-v2.fattureincloud.it
tags:
  - name: Archive
  - name: Cashbook
  - name: Clients
  - name: Companies
  - name: Info
  - name: Issued Documents
  - name: Issued e-invoices
  - name: Products
  - name: Receipts
  - name: Received Documents
  - name: Suppliers
  - name: Taxes
  - name: User
paths:
  /user/info:
    get:
      tags:
        - User
      summary: Get User Info
      operationId: getUserInfo
      description: Gets the current user's info.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /user/companies:
    get:
      summary: List User Companies
      tags:
        - User
      operationId: listUserCompanies
      description: Lists the companies controlled by the current user.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/company/info:
    get:
      summary: Get Company Info
      operationId: getCompanyInfo
      description: Gets the company detailed info.
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Companies
  /c/{company_id}/entities/clients:
    get:
      summary: List Clients
      tags:
        - Clients
      operationId: listClients
      description: Lists the clients.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.clients:r
    post:
      summary: Create Client
      operationId: createClient
      description: Creates a new client.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.clients:a
      tags:
        - Clients
  /c/{company_id}/entities/clients/{client_id}:
    get:
      summary: Get Client
      tags:
        - Clients
      operationId: getClient
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.clients:r
      description: Gets the specified client.
    put:
      summary: Modify Client
      operationId: modifyClient
      description: Modifies the specified client.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.clients:a
      tags:
        - Clients
    delete:
      summary: Delete Client
      operationId: deleteClient
      description: Deletes the specified client.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.clients:a
      tags:
        - Clients
  /c/{company_id}/entities/suppliers:
    get:
      summary: List Suppliers
      operationId: listSuppliers
      description: Lists the suppliers.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.suppliers:r
      tags:
        - Suppliers
    post:
      summary: Create Supplier
      operationId: createSupplier
      description: Creates a new supplier.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.suppliers:a
      tags:
        - Suppliers
  /c/{company_id}/entities/suppliers/{supplier_id}:
    get:
      summary: Get Supplier
      operationId: getSupplier
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.suppliers:r
      description: Gets the specified supplier.
      tags:
        - Suppliers
    put:
      summary: Modify Supplier
      operationId: modifySupplier
      description: Modifies the specified supplier.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.suppliers:a
      tags:
        - Suppliers
    delete:
      summary: Delete Supplier
      operationId: deleteSupplier
      description: Deletes the specified supplier.
      security:
        - OAuth2AuthenticationCodeFlow:
            - entity.suppliers:a
      tags:
        - Suppliers
  /c/{company_id}/products:
    get:
      summary: List Products
      tags:
        - Products
      operationId: listProducts
      description: Lists the products.
      security:
        - OAuth2AuthenticationCodeFlow:
            - products:r
    post:
      summary: Create Product
      operationId: createProduct
      tags:
        - Products
      description: Creates a new product.
      security:
        - OAuth2AuthenticationCodeFlow:
            - products:a
  /c/{company_id}/products/{product_id}:
    get:
      summary: Get Product
      tags:
        - Products
      operationId: getProduct
      description: Gets the specified product.
      security:
        - OAuth2AuthenticationCodeFlow:
            - products:r
    put:
      summary: Modify Product
      operationId: modifyProduct
      description: Modifies the specified product.
      security:
        - OAuth2AuthenticationCodeFlow:
            - products:a
      tags:
        - Products
    delete:
      summary: Delete Product
      operationId: deleteProduct
      description: Deletes the specified product.
      security:
        - OAuth2AuthenticationCodeFlow:
            - products:a
      tags:
        - Products
  /c/{company_id}/issued_documents:
    get:
      summary: List Issued Documents
      tags:
        - Issued Documents
      operationId: listIssuedDocuments
      description: Lists the issued documents.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:r
            - issued_documents.credit_note:r
            - issued_documents.receipt:r
            - issued_documents.order:r
            - issued_documents.quote:r
            - issued_documents.proforma:r
            - issued_documents.delivery_note:r
    post:
      summary: Create Issued Document
      operationId: createIssuedDocument
      tags:
        - Issued Documents
      description: Creates a new document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:a
            - issued_documents.credit_note:a
            - issued_documents.receipt:a
            - issued_documents.order:a
            - issued_documents.quote:a
            - issued_documents.proforma:a
            - issued_documents.delivery_note:a
  /c/{company_id}/issued_documents/{document_id}:
    get:
      summary: Get Issued Document
      tags:
        - Issued Documents
      operationId: getIssuedDocument
      description: |
        Gets the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:r
            - issued_documents.credit_note:r
            - issued_documents.receipt:r
            - issued_documents.order:r
            - issued_documents.quote:r
            - issued_documents.proforma:r
            - issued_documents.delivery_note:r
    put:
      summary: Modify Issued Document
      operationId: modifyIssuedDocument
      description: Modifies the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:a
            - issued_documents.credit_note:a
            - issued_documents.receipt:a
            - issued_documents.order:a
            - issued_documents.quote:a
            - issued_documents.proforma:a
            - issued_documents.delivery_note:a
      tags:
        - Issued Documents
    delete:
      summary: Delete Issued Document
      operationId: deleteIssuedDocument
      description: Deletes the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:a
            - issued_documents.credit_note:a
            - issued_documents.receipt:a
            - issued_documents.order:a
            - issued_documents.quote:a
            - issued_documents.proforma:a
            - issued_documents.delivery_note:a
      tags:
        - Issued Documents
  /c/{company_id}/issued_documents/totals:
    post:
      summary: Get New Issued Document Totals
      operationId: getNewIssuedDocumentTotals
      description: Returns the totals for a new document.
      tags:
        - Issued Documents
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/{document_id}/totals:
    post:
      summary: Get Existing Issued Document Totals
      operationId: getExistingIssuedDocumentTotals
      tags:
        - Issued Documents
      description: Returns the totals for a specified document.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/attachment:
    post:
      summary: Upload Issued Document Attachment
      operationId: uploadIssuedDocumentAttachment
      tags:
        - Issued Documents
      description: >-
        Uploads an attachment destined to an issued document. The actual
        association between the document and the attachment must be implemented
        separately, using the returned token.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/{document_id}/attachment:
    delete:
      summary: Delete Issued Document Attachment
      operationId: deleteIssuedDocumentAttachment
      description: Removes the attachment of the specified document.
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Issued Documents
  /c/{company_id}/issued_documents/info:
    get:
      summary: Get Issued Document Pre-create info
      tags:
        - Issued Documents
      operationId: getIssuedDocumentPreCreateInfo
      description: Retrieves the information useful while creating a new document.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/{document_id}/email:
    get:
      summary: Get Email Data
      tags:
        - Issued Documents
      operationId: getEmailData
      description: Gets the pre-compiled email details.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:r
            - issued_documents.credit_note:r
            - issued_documents.receipt:r
            - issued_documents.order:r
            - issued_documents.quote:r
            - issued_documents.proforma:r
            - issued_documents.delivery_note:r
    post:
      summary: Schedule Email
      operationId: scheduleEmail
      description: Schedules the sending of a document by email.
      security:
        - OAuth2AuthenticationCodeFlow:
            - issued_documents.invoice:r
            - issued_documents.credit_note:r
            - issued_documents.receipt:r
            - issued_documents.order:r
            - issued_documents.quote:r
            - issued_documents.proforma:r
            - issued_documents.delivery_note:r
      tags:
        - Issued Documents
  /c/{company_id}/issued_documents/{document_id}/e_invoice/send:
    post:
      summary: Send the e-invoice
      operationId: sendEInvoice
      description: Sends the e-invoice to SDI.
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Issued e-invoices
  /c/{company_id}/issued_documents/{document_id}/e_invoice/xml_verify:
    get:
      summary: Verify e-invoice xml
      tags:
        - Issued e-invoices
      operationId: verifyEInvoiceXml
      description: >-
        Verifies the e-invoice xml format. Checks if all of the mandatory fields
        are filled and compliant to the right format.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/{document_id}/e_invoice/xml:
    get:
      summary: Get e-invoice XML
      tags:
        - Issued e-invoices
      operationId: getEInvoiceXml
      description: Downloads the e-invoice in XML format.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/issued_documents/{document_id}/e_invoice/error_reason:
    get:
      summary: Get EInvoice rejection reason
      tags:
        - Issued e-invoices
      operationId: getEInvoiceRejectionReason
      description: Get EInvoice rejection reason
  /c/{company_id}/received_documents:
    get:
      summary: List Received Documents
      tags:
        - Received Documents
      operationId: listReceivedDocuments
      description: Lists the received documents.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:r
            - stock:r
    post:
      summary: Create Received Document
      operationId: createReceivedDocument
      description: Creates a new document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
      tags:
        - Received Documents
  /c/{company_id}/received_documents/{document_id}:
    get:
      summary: Get Received Document
      tags:
        - Received Documents
      operationId: getReceivedDocument
      description: Gets the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:r
            - stock:r
    put:
      summary: Modify Received Document
      operationId: modifyReceivedDocument
      tags:
        - Received Documents
      description: Modifies the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
    delete:
      summary: Delete Received Document
      operationId: deleteReceivedDocument
      tags:
        - Received Documents
      description: Deletes the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
  /c/{company_id}/received_documents/totals:
    post:
      summary: Get New Received Document Totals
      operationId: getNewReceivedDocumentTotals
      description: Returns the totals for a new document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
      tags:
        - Received Documents
  /c/{company_id}/received_documents/{document_id}/totals:
    post:
      summary: Get Existing Received Document Totals
      operationId: getExistingReceivedDocumentTotals
      tags:
        - Received Documents
      description: Returns the totals for the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
  /c/{company_id}/received_documents/attachment:
    post:
      summary: Upload Received Document Attachment
      operationId: uploadReceivedDocumentAttachment
      tags:
        - Received Documents
      description: >-
        Uploads an attachment destined to a received document. The actual
        association between the document and the attachment must be implemented
        separately, using the returned token.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
  /c/{company_id}/received_documents/{document_id}/attachment:
    delete:
      summary: Delete Received Document Attachment
      operationId: deleteReceivedDocumentAttachment
      tags:
        - Received Documents
      description: Removes the attachment of the specified document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:a
            - stock:a
  /c/{company_id}/received_documents/info:
    get:
      summary: Get Received Document Pre-Create Info
      tags:
        - Received Documents
      operationId: getReceivedDocumentPreCreateInfo
      description: Retrieves the information useful while creating a new document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - received_documents:r
  /c/{company_id}/receipts:
    get:
      summary: List Receipts
      tags:
        - Receipts
      operationId: listReceipts
      description: Lists the receipts.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:r
    post:
      summary: Create Receipt
      operationId: createReceipt
      description: Creates a new receipt.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:a
      tags:
        - Receipts
  /c/{company_id}/receipts/{document_id}:
    get:
      summary: Get Receipt
      tags:
        - Receipts
      operationId: getReceipt
      description: Gets the specified receipt.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:r
    put:
      summary: Modify Receipt
      operationId: modifyReceipt
      tags:
        - Receipts
      description: Modifies the specified receipt.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:a
    delete:
      summary: Delete Receipt
      operationId: deleteReceipt
      description: Deletes the specified receipt.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:a
      tags:
        - Receipts
  /c/{company_id}/receipts/info:
    get:
      summary: Get Receipt Pre-Create Info
      tags:
        - Receipts
      operationId: getReceiptPreCreateInfo
      description: Retrieves the information useful while creating a new receipt.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:r
  /c/{company_id}/receipts/monthly_totals:
    get:
      summary: Get Receipts Monthly Totals
      tags:
        - Receipts
      operationId: getReceiptsMonthlyTotals
      description: Returns the monthly totals by year and receipt type.
      security:
        - OAuth2AuthenticationCodeFlow:
            - receipts:r
  /c/{company_id}/taxes:
    get:
      summary: List F24
      tags:
        - Taxes
      operationId: listF24
      description: Lists the F24s.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:r
    post:
      summary: Create F24
      operationId: createF24
      tags:
        - Taxes
      description: Creates a new F24.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:a
  /c/{company_id}/taxes/{document_id}:
    get:
      summary: Get F24
      tags:
        - Taxes
      operationId: getF24
      description: Gets the specified F24.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:r
    put:
      summary: Modify F24
      operationId: modifyF24
      description: Modifies the specified F24.
      tags:
        - Taxes
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:a
    delete:
      summary: Delete F24
      operationId: deleteF24
      tags:
        - Taxes
      description: Removes the specified F24.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:a
  /c/{company_id}/taxes/attachment:
    post:
      summary: Upload F24 Attachment
      tags:
        - Taxes
      operationId: uploadF24Attachment
      description: >-
        Uploads an attachment destined to a F24. The actual association between
        the document and the attachment must be implemented separately, using
        the returned token.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:a
  /c/{company_id}/taxes/{document_id}/attachment:
    delete:
      summary: Delete F24 Attachment
      tags:
        - Taxes
      operationId: deleteF24Attachment
      description: Removes the attachment of the specified F24.
      security:
        - OAuth2AuthenticationCodeFlow:
            - taxes:a
  /c/{company_id}/archive:
    get:
      summary: List Archive Documents
      tags:
        - Archive
      operationId: listArchiveDocuments
      description: Lists the archive documents.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:r
    post:
      summary: Create Archive Document
      operationId: createArchiveDocument
      tags:
        - Archive
      description: Creates a new archive document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:a
  /c/{company_id}/archive/{document_id}:
    get:
      summary: Get Archive Document
      tags:
        - Archive
      operationId: getArchiveDocument
      description: Gets the specified archive document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:r
    put:
      summary: Modify Archive Document
      operationId: modifyArchiveDocument
      tags:
        - Archive
      description: Modifies the specified archive document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:a
    delete:
      summary: Delete Archive Document
      operationId: deleteArchiveDocument
      tags:
        - Archive
      description: Deletes the specified archive document.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:a
  /c/{company_id}/archive/attachment:
    post:
      summary: Upload Archive Document Attachment
      tags:
        - Archive
      operationId: uploadArchiveDocumentAttachment
      description: >-
        Uploads an attachment destined to an archive document. The actual
        association between the document and the attachment must be implemented
        separately, using the returned token.
      security:
        - OAuth2AuthenticationCodeFlow:
            - archive:a
  /c/{company_id}/cashbook:
    get:
      summary: List Cashbook Entries
      tags:
        - Cashbook
      operationId: listCashbookEntries
      description: Lists the cashbook entries.
      security:
        - OAuth2AuthenticationCodeFlow:
            - cashbook:r
    post:
      summary: Create Cashbook Entry
      operationId: createCashbookEntry
      tags:
        - Cashbook
      description: Creates a new cashbook entry.
      security:
        - OAuth2AuthenticationCodeFlow:
            - cashbook:a
  /c/{company_id}/cashbook/{document_id}:
    get:
      summary: Get Cashbook Entry
      tags:
        - Cashbook
      operationId: getCashbookEntry
      description: Gets the specified cashbook entry.
      security:
        - OAuth2AuthenticationCodeFlow:
            - cashbook:r
    put:
      summary: Modify Cashbook Entry
      operationId: modifyCashbookEntry
      tags:
        - Cashbook
      description: Modifies the specified cashbook entry.
      security:
        - OAuth2AuthenticationCodeFlow:
            - cashbook:a
    delete:
      summary: Delete Cashbook Entry
      operationId: deleteCashbookEntry
      description: Deletes the specified cashbook entry.
      security:
        - OAuth2AuthenticationCodeFlow:
            - cashbook:a
      tags:
        - Cashbook
  /info/countries:
    get:
      summary: List Countries
      tags:
        - Info
      operationId: listCountries
      description: Lists the supported countries.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/cities:
    get:
      summary: List Cities
      tags:
        - Info
      operationId: listCities
      description: Lists the Italian cities.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/languages:
    get:
      summary: List Languages
      tags:
        - Info
      operationId: listLanguages
      description: Lists the supported languages.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/templates:
    get:
      summary: List Templates
      tags:
        - Info
      operationId: listTemplates
      description: Lists the available templates.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/currencies:
    get:
      summary: List Currencies
      tags:
        - Info
      operationId: listCurrencies
      description: Lists the supported currencies.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/measures:
    get:
      summary: List Units of Measure
      tags:
        - Info
      operationId: listUnitsOfMeasure
      description: Lists the units of measure.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/dn_causals:
    get:
      summary: List Delivery Notes Default Causals
      tags:
        - Info
      operationId: listDeliveryNotesDefaultCausals
      description: Lists the delivery note default causals.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/vat_types:
    get:
      summary: List Vat Types
      tags:
        - Info
      operationId: listVatTypes
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:r
      description: Lists the available vat types.
  /c/{company_id}/info/payment_methods:
    get:
      summary: List Payment Methods
      tags:
        - Info
      operationId: listPaymentMethods
      description: Lists the available payment methods.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/payment_accounts:
    get:
      summary: List Payment Accounts
      tags:
        - Info
      operationId: listPaymentAccounts
      description: Lists the available payment accounts.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/revenue_centers:
    get:
      summary: List Revenue Centers
      tags:
        - Info
      operationId: listRevenueCenters
      description: Lists the revenue centers.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/cost_centers:
    get:
      summary: List Cost Centers
      tags:
        - Info
      operationId: listCostCenters
      description: Lists the cost centers.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/product_categories:
    get:
      summary: List Product Categories
      tags:
        - Info
      operationId: listProductCategories
      description: Lists the product categories.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/received_document_categories:
    get:
      summary: List Received Document Categories
      tags:
        - Info
      operationId: listReceivedDocumentCategories
      description: Lists the received document categories.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/info/archive_categories:
    get:
      summary: List Archive Categories
      tags:
        - Info
      operationId: listArchiveCategories
      description: Lists the archive categories.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /c/{company_id}/settings/payment_methods:
    post:
      summary: Create Payment Method
      tags:
        - Settings
      operationId: createPaymentMethod
      description: Creates a new payment method.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
  /c/{company_id}/settings/payment_methods/{payment_method_id}:
    get:
      summary: Get Payment Method
      tags:
        - Settings
      operationId: getPaymentMethod
      description: Gets the specified payment method.
      security:
        - OAuth2AuthenticationCodeFlow: []
    put:
      summary: Modify Payment Method
      tags:
        - Settings
      operationId: modifyPaymentMethod
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
      description: Modifies the specified payment method.
    delete:
      summary: Delete Payment Method
      tags:
        - Settings
      operationId: deletePaymentMethod
      description: Deletes the specified payment method.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
  /c/{company_id}/settings/payment_accounts:
    post:
      summary: Create Payment Account
      tags:
        - Settings
      operationId: createPaymentAccount
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
      description: Creates a new payment account.
  /c/{company_id}/settings/payment_accounts/{payment_account_id}:
    get:
      summary: Get Payment Account
      tags:
        - Settings
      operationId: getPaymentAccount
      description: Gets the specified payment account.
      security:
        - OAuth2AuthenticationCodeFlow: []
    put:
      summary: Modify Payment Account
      tags:
        - Settings
      operationId: modifyPaymentAccount
      description: Modifies the specified payment account.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
    delete:
      summary: Delete Payment Account
      tags:
        - Settings
      operationId: deletePaymentAccount
      description: Deletes the specified payment account.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
  /c/{company_id}/settings/vat_types:
    post:
      summary: Create Vat Type
      tags:
        - Settings
      operationId: createVatType
      description: Creates a vat type.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
  /c/{company_id}/settings/vat_types/{vat_type_id}:
    get:
      summary: Get Vat Type
      tags:
        - Settings
      operationId: getVatType
      description: Gets the specified vat type.
      security:
        - OAuth2AuthenticationCodeFlow: []
    put:
      summary: Modify Vat Type
      tags:
        - Settings
      operationId: modifyVatType
      description: Modifies the specified vat type.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
    delete:
      summary: Delete Vat Type
      tags:
        - Settings
      operationId: deleteVatType
      description: Deletes the specified vat type.
      security:
        - OAuth2AuthenticationCodeFlow:
            - settings:a
components:
  securitySchemes:
    OAuth2AuthenticationCodeFlow:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: https://api-v2.fattureincloud.it/oauth/token
          refreshUrl: https://api-v2.fattureincloud.it/oauth/token
          scopes:
            entity.clients:r: ''
            entity.clients:a: ''
            entity.suppliers:r: ''
            entity.suppliers:a: ''
            products:r: ''
            products:a: ''
            issued_documents.invoice:r: ''
            issued_documents.credit_note:r: ''
            issued_documents.receipt:r: ''
            issued_documents.order:r: ''
            issued_documents.quote:r: ''
            issued_documents.proforma:r: ''
            issued_documents.delivery_note:r: ''
            issued_documents.invoice:a: ''
            issued_documents.credit_note:a: ''
            issued_documents.receipt:a: ''
            issued_documents.order:a: ''
            issued_documents.quote:a: ''
            issued_documents.proforma:a: ''
            issued_documents.delivery_note:a: ''
            received_documents:r: ''
            received_documents:a: ''
            stock:r: ''
            stock:a: ''
            receipts:r: ''
            receipts:a: ''
            taxes:r: ''
            taxes:a: ''
            archive:r: ''
            archive:a: ''
            cashbook:r: ''
            cashbook:a: ''
            settings:r: ''
            settings:a: ''
            situation:r: ''
          authorizationUrl: https://api-v2.fattureincloud.it/oauth/authorize
security:
  - OAuth2AuthenticationCodeFlow: []
