openapi: 3.1.0
info:
  title: Fatture in Cloud API v2 - API Reference
  description: "## Request informations\nIn every request description you will be able to find some additional informations about context, permissions and supported functionality:\n\n| Parameter | Description |\n|-----------|-------------|\n| \U0001F465 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  |\n| \U0001F512 Required scope | If present, indicates the required scope to fulfill the request. |\n| \U0001F50D Filtering | If present, indicates which fi[...]"
  contact:
    name: Fatture in Cloud
    url: 'https://www.fattureincloud.it'
    email: info@fattureincloud.it
  license:
    name: ''
    url: 'https://www.fattureincloud.it'
  version: v2.0
servers:
  - url: 'https://api-v2.fattureincloud.it'
tags:
  - name: Clients
  - name: Issued Documents
  - name: Products
  - name: Suppliers
  - name: User
paths:
  /user/info:
    get:
      tags:
        - User
      summary: Get user info
      operationId: userInfo
      description: "Makes possible to retrieve the current user's info.\n\n\U0001F464 Person context\n\nGet user email, name and id."
      security:
        - OAuth2AuthenticationCodeFlow: []
  /user/companies:
    get:
      summary: userCompanies
      tags:
        - User
      operationId: userCompanies
      description: "\U0001F464 Person context\n\nGet a list of the controlled companies and their CompanyAuthentication tokens."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{companyId}/company/info':
    get:
      summary: Your GET endpoint
      tags:
        - Company
      operationId: companyInfo
      description: 'Get company info like email, license expire date and access info for each document and section'
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{companyId}/entities/clients':
    get:
      summary: List Clients
      tags:
        - Clients
      operationId: listClients
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:r\n\U0001F50D Filtering: id, code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes, imported, atoka_show, e_invoice, ei_code, created_at, updated_at\n↕️ Sorting: code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, [...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:r'
    post:
      summary: Create Client
      operationId: createClient
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:a`\n\nCreate a new client."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
  '/c/{companyId}/entities/suppliers':
    get:
      summary: List Suppliers
      operationId: listSuppliers
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:r\n\U0001F50D Filtering: id, code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes, imported, atoka_show, created_at, updated_at\n↕️ Sorting: code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes,[...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:r'
      tags:
        - Suppliers
    post:
      summary: Create Supplier
      operationId: createSupplier
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.suppliers:a`\n\nCreate a new supplier."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
  '/c/{companyId}/entities/clients/{clientId}':
    get:
      summary: Get Client
      tags:
        - Clients
      operationId: getClient
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:r'
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing client by its unique id."
    put:
      summary: Modify Client
      operationId: modifyClient
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:a\n\nEdit an existing client by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
    delete:
      summary: Delete Client
      operationId: deleteClient
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:a\n\nDelete an existing client by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
  '/c/{companyId}/entities/suppliers/{supplierId}':
    get:
      summary: Get Supplier
      operationId: getSupplier
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:r'
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing supplier by its unique id."
      tags:
        - Suppliers
    put:
      summary: Modify Supplier
      operationId: modifySupplier
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:a\n\nEdit an existing supplier by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
    delete:
      summary: Delete Supplier
      operationId: deleteSupplier
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:a\n\nDelete an existing supplier by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
  '/c/{companyId}/products':
    get:
      summary: List Products
      tags:
        - Products
      operationId: listProducts
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:r\n\U0001F50D Filtering: id, name, code, net_price, gross_price, net_cost, description, category, notes, in_stock, created_at, updated_at\n↕️ Sorting: name, code, net_price, gross_price, net_cost, description, category, notes, in_stock, created_at, updated_at\n\U0001F4C4 Paginated results\n\U0001F3A9 Customized responses supported\n\nGet a list of products that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:r'
    post:
      summary: ''
      operationId: createProduct
      tags:
        - Products
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:a\n\nCreate a new product."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
  '/c/{companyId}/products/{productId}':
    get:
      summary: Get Product
      tags:
        - Products
      operationId: getProduct
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:r\n\U0001F3A9 Customized responses supported\n\nGet product details"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:r'
    put:
      summary: Modify Product
      operationId: modifyProduct
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:a\n\nEdit an existing product by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
      tags:
        - Products
    delete:
      summary: ''
      operationId: deleteProduct
      description: Delete Product
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
      tags:
        - Products
  '/c/{companyId}/issued_documents':
    get:
      summary: List Issued Documents
      tags:
        - Issued Documents
      operationId: listIssuedDocuments
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:r\n\U0001F50D Filtering: type, entity.id, entity.name, entity.vat_number, entity.tax_code, entity.city, entity.province, entity.country, date, number, numeration, any_subject, amount_net, amount_vat, amount_gross, next_due_date, created_at, updated_at\n↕️ Sorting: entity.id, entity.name, entity.vat_number, entity.tax_code, entity.city, entity.province, entity.country, date, number, numerati[...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:r'
            - 'issued_documents.credit_note:r'
            - 'issued_documents.receipt:r'
            - 'issued_documents.order:r'
            - 'issued_documents.quote:r'
            - 'issued_documents.proforma:r'
            - 'issued_documents.delivery_note:r'
    post:
      summary: Create Issued Document
      operationId: createIssuedDocument
      tags:
        - Issued Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:a\n\nCreate a new document."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:a'
            - 'issued_documents.credit_note:a'
            - 'issued_documents.receipt:a'
            - 'issued_documents.order:a'
            - 'issued_documents.quote:a'
            - 'issued_documents.proforma:a'
            - 'issued_documents.delivery_note:a'
components:
  securitySchemes:
    OAuth2AuthenticationCodeFlow:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: 'https://api-v2.fattureincloud.it/oauth/token'
          refreshUrl: ''
          scopes:
            'entity.clients:r': ''
            'entity.clients:a': ''
            'entity.suppliers:r': ''
            'entity.suppliers:a': ''
            'products:r': ''
            'products:a': ''
            'issued_documents.invoice:r': ''
            'issued_documents.credit_note:r': ''
            'issued_documents.receipt:r': ''
            'issued_documents.order:r': ''
            'issued_documents.quote:r': ''
            'issued_documents.proforma:r': ''
            'issued_documents.delivery_note:r': ''
            'issued_documents.invoice:a': ''
            'issued_documents.credit_note:a': ''
            'issued_documents.receipt:a': ''
            'issued_documents.order:a': ''
            'issued_documents.quote:a': ''
            'issued_documents.proforma:a': ''
            'issued_documents.delivery_note:a': ''
          authorizationUrl: 'https://api-v2.fattureincloud.it/oauth/authorize'
security:
  - OAuth2AuthenticationCodeFlow: []
