openapi: 3.0.1
info:
  title: Fatture in Cloud API v2 - API Reference
  description: "## Request informations\nIn every request description you will be able to find some additional informations about context, permissions and supported functionality:\n\n| Parameter | Description |\n|-----------|-------------|\n| \U0001F465 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  |\n| \U0001F512 Required scope | If present, indicates the required scope to fulfill the request. |\n| \U0001F50D Filtering | If present, indicates which fi[...]"
  contact:
    name: Fatture in Cloud
    url: 'https://www.fattureincloud.it'
    email: info@fattureincloud.it
  license:
    name: ''
  version: v1.0
servers:
  - url: 'https://api-v2.fattureincloud.it/'
tags:
  - name: Auth
    description: Autenticazione
  - name: User
    description: Utente
  - name: Company
    description: Azienda
  - name: Clients and suppliers
    description: Clienti e fornitori
  - name: Products
    description: Prodotti
  - name: Issued documents
  - name: Issued e-invoices
  - name: Received documents
  - name: Received e-invoices
  - name: E-invoices
  - name: Receipts
  - name: Taxes
  - name: Archive
  - name: Info
  - name: Settings
  - name: Cashbook
  - name: Search
  - name: Dashboard
  - name: Calendar
  - name: Notifications
  - name: No authentication
  - name: Entities
  - name: TEST
paths:
  /user/info:
    get:
      tags:
        - User
      summary: Get user info
      description: "\U0001F464 Person context\n\nGet user email, name and id."
      operationId: userInfo
      security:
        - OAuth2Authentication:
            - no scope required
  /user/companies:
    get:
      tags:
        - User
      summary: Get controlled companies
      description: "\U0001F464 Person context\n\nGet a list of the controlled companies and their CompanyAuthentication tokens."
      operationId: userCompanies
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/company/info':
    get:
      tags:
        - Company
      summary: Get company info
      description: 'Get company info like email, license expire date and access info for each document and section'
      operationId: companyInfo
      security:
        - OAuth2Authentication:
            - no scope required
      x-private: true
  '/c/{companyId}/entities/{entityRole}':
    get:
      tags:
        - Clients and suppliers
      summary: List and search entities
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole`) \\\n\U0001F50D Filtering: `id`, `code`, `name`, `type`, `vat_number`, `tax_code`, `address_street`, `address_postal_code`, `address_city`, `address_province`, `country`, `email`, `certified_email`, `phone`, `fax`, `notes`, `imported`, `atoka_show`, `e_invoice`, `ei_code`, `created_at`, `updated_at` \\\n↕️ Sorting: `code`, `name`, `type`, `vat_number[...]"
      operationId: entitiesList
      security:
        - OAuth2Authentication:
            - 'entity.clients:r'
            - 'entity.suppliers:r'
    post:
      tags:
        - Clients and suppliers
      summary: Create entity
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:a` or `entity.suppliers:a` (depending on `entityRole` parameter)\n\nCreate a new entity (client or supplier)."
      operationId: entitiesCreate
      security:
        - OAuth2Authentication:
            - 'entity.clients:a'
            - 'entity.suppliers:a'
  '/c/{companyId}/entities/{entityRole}/{entityId}':
    get:
      tags:
        - Clients and suppliers
      summary: Get entity details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:r` or `entity.suppliers:r` (depending on `entityRole` parameter) \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing entity by its unique id."
      operationId: entitiesDetails
      security:
        - OAuth2Authentication:
            - 'entity.clients:r'
            - 'entity.suppliers:r'
    put:
      tags:
        - Clients and suppliers
      summary: Edit an entity
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:a` or `entity.suppliers:a` (depending on `entityRole` parameter)\n\nEdit an existing entity by its unique id."
      operationId: entitiesEdit
      security:
        - OAuth2Authentication:
            - 'entity.clients:a'
            - 'entity.suppliers:a'
    delete:
      tags:
        - Clients and suppliers
      summary: Remove an entity
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:a` or `entity.suppliers:a` (depending on `entityRole` parameter)\n\nDelete an existing entity by its unique id."
      operationId: entitiesRemove
      security:
        - OAuth2Authentication:
            - 'entity.clients:a'
            - 'entity.suppliers:a'
  '/c/{companyId}/products':
    get:
      tags:
        - Products
      summary: List and search products
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `products:r` \\\n\U0001F50D Filtering: `id`, `name`, `code`, `net_price`, `gross_price`, `net_cost`, `description`, `category`, `notes`, `in_stock`, `created_at`, `updated_at` \\\n↕️ Sorting: `name`, `code`, `net_price`, `gross_price`, `net_cost`, `description`, `category`, `notes`, `in_stock`, `created_at`, `updated_at` \\\n\U0001F4C4 Paginated results \\\n\U0001F3A9 Customized responses supported\n\nGet a list of pro[...]"
      operationId: productsList
      security:
        - OAuth2Authentication:
            - 'products:r'
      x-internal: false
    post:
      tags:
        - Products
      summary: Create product
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `products:a`\n\nCreate a new product."
      operationId: productsCreate
      security:
        - OAuth2Authentication:
            - 'products:a'
  '/c/{companyId}/products/{productId}':
    get:
      tags:
        - Products
      summary: Product details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `products:r` \\\n\U0001F3A9 Customized responses supported\n\nGet product details"
      operationId: productsDetails
      security:
        - OAuth2Authentication:
            - 'products:r'
    put:
      tags:
        - Products
      summary: Edit a product
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `products:a`\n\nEdit an existing product by its unique id."
      operationId: productsEdit
      security:
        - OAuth2Authentication:
            - 'products:a'
    delete:
      tags:
        - Products
      summary: Remove a product
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `products:a`\n\nDelete an existing product by its unique id."
      operationId: productsRemove
      security:
        - OAuth2Authentication:
            - 'products:a'
  '/c/{companyId}/issued_documents':
    get:
      tags:
        - Issued documents
      summary: List and search documents
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:r` \\\n\U0001F50D Filtering: `type`, `entity.id`, `entity.name`, `entity.vat_number`, `entity.tax_code`, `entity.city`, `entity.province`, `entity.country`, `date`, `number`, `numeration`, `any_subject`, `amount_net`, `amount_vat`, `amount_gross`, `next_due_date`, `created_at`, `updated_at`  \\\n↕️ Sorting: `entity.id`, `entity.name`, `entity.vat_number`, `entity.tax_code`, `entity.city[...]"
      operationId: issuedDocumentsList
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:r'
    post:
      tags:
        - Issued documents
      summary: Create new document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:a`\n\nCreate a new document."
      operationId: issuedDocumentsCreate
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:a'
  '/c/{companyId}/issued_documents/{documentId}':
    get:
      tags:
        - Issued documents
      summary: Get document details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: issuedDocumentDetails
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:r'
    put:
      tags:
        - Issued documents
      summary: Edit a document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:a`\n\nEdit an existing document by its unique id."
      operationId: issuedDocumentEdit
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:a'
    delete:
      tags:
        - Issued documents
      summary: Remove a document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:a`\n\nDelete an existing document by its unique id."
      operationId: issuedDocumentRemove
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:a'
  '/c/{companyId}/issued_documents/totals':
    post:
      tags:
        - Issued documents
      summary: Get new document totals
      description: "\U0001F465 Company context\n\nGet the totals of a document"
      operationId: issuedDocumentTotals
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/{documentId}/totals':
    post:
      tags:
        - Issued documents
      summary: Get existing document totals
      description: "\U0001F465 Company context\n\nGet existing document totals"
      operationId: issuedDocumentsTotal
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/attachment':
    post:
      tags:
        - Issued documents
      summary: Upload attachment
      description: "\U0001F465 Company context\n\nUpload an attachment to an issued document"
      operationId: issuedDocumentsAttachment
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/{documentId}/attachment':
    delete:
      tags:
        - Issued documents
      summary: Remove the attachment
      description: "\U0001F465 Company context\n\nRemove the attachment (but not the document)"
      operationId: issuedDocumentsAttachmentRemove
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/info':
    get:
      tags:
        - Issued documents
      summary: Pre-create info
      description: "\U0001F465 Company context\n\nGet the info needed for the document creation flow."
      operationId: issuedDocumentInfo
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/{documentId}/preview':
    get:
      tags:
        - Issued documents
      summary: Document HTML preview
      description: "\U0001F465 Company context\n\nRetrieve the HTML preview of the document."
      operationId: issuedDocumentsPreview
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/{documentId}/email':
    get:
      tags:
        - Issued documents
      summary: Get email data
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:r`\n\nGet pre-compiled email data like subject, body, attachments, SMTP credentials, CC, recipients list."
      operationId: issuedDocumentsEmailGet
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:r'
    post:
      tags:
        - Issued documents
      summary: Schedule email
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `issued_documents.[documentType]:r`\n\nSchedule email sending of a document."
      operationId: issuedDocumentsEmail
      security:
        - OAuth2Authentication:
            - 'issued_documents.[documentType]:r'
  '/c/{companyId}/issued_documents/{documentId}/e_invoice/send':
    post:
      tags:
        - Issued e-invoices
      summary: Send the e-invoice
      description: "\U0001F465 Company context\n\nSend the e-invoice to SDI"
      operationId: issuedDocumentsSednEInvoice
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/received_documents':
    get:
      tags:
        - Received documents
      summary: List and search documents
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:r` (but if the document is a `passive_delivery_note` you'll need `stock:r` scope) \\\n\U0001F50D Filtering: `id`, `type`, `category`, `description`, `entity.id`, `entity.name`, `date`, `next_due_date`, `amount_gross`, `amount_net`, `amount_vat`, `invoice_number`, `created_at`, `updated_at` \\\n↕️ Sorting: `id`, `category`, `entity.id`, `entity.name`, `date`, `next_due_date`, `amount_gross`, `amount_[...]"
      operationId: receivedDocumentsList
      security:
        - OAuth2Authentication:
            - 'received_documents:r'
    post:
      tags:
        - Received documents
      summary: New document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nCreate a new received document."
      operationId: receivedDocumentsCreate
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/{documentId}':
    get:
      tags:
        - Received documents
      summary: Get document details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:r` (but if the document is a `passive_delivery_note` you'll need `stock:r` scope) \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: receivedDocumentsDetails
      security:
        - OAuth2Authentication:
            - 'received_documents:r'
    put:
      tags:
        - Received documents
      summary: Edit a document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nEdit an existing document by its unique id."
      operationId: receivedDocumentsEdit
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
    delete:
      tags:
        - Received documents
      summary: Remove a document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nDelete an existing document by its unique id."
      operationId: receivedDocumentsDelete
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/totals':
    post:
      tags:
        - Received documents
      summary: New document totals
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nCalculate totals of the received document passed in the body."
      operationId: receivedDocumentsTotal
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/{documentId}/totals':
    post:
      tags:
        - Received documents
      summary: Get existing document totals
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nCalculate totals of the received document indicated by the id with the changes passed in the body.\n"
      operationId: receivedDocumentsSingleTotal
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/attachment':
    post:
      tags:
        - Received documents
      summary: Upload attachment
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nUpload an attachment and return the relative token."
      operationId: receivedDocumentsAttachment
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/{documentId}/attachment':
    delete:
      tags:
        - Received documents
      summary: Remove the attachment
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:a` (but if the document is a `passive_delivery_note` you'll need `stock:a` scope)\n\nRemove the attachment (but not the document)"
      operationId: receivedDocumentsSingleAttachment
      security:
        - OAuth2Authentication:
            - 'received_documents:a'
  '/c/{companyId}/received_documents/info':
    get:
      tags:
        - Received documents
      summary: Pre-create info
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `received_documents:r`\n\nGet the info needed for the document creation flow."
      operationId: receivedDocumentsInfo
      security:
        - OAuth2Authentication:
            - 'received_documents:r'
  /e_invoices/preview:
    get:
      tags:
        - E-invoices
        - Issued e-invoices
        - Received e-invoices
      summary: Preview an e-invoice
      description: 'Get styled xml of an electronic invoice if **html parameter** has been set to true, otherwise return xml file.'
      operationId: einvoicePreview
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/taxes':
    get:
      tags:
        - Taxes
      summary: List and search F24
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:r` \\\n\U0001F50D Filtering: `due_date`, `status`, `amount`, `description` \\\n↕️ Sorting: `due_date`, `status`, `amount`, `description` \\\n\U0001F4C4 Paginated results \\\n\U0001F3A9 Customized responses supported\n\nGet a list of F24 that match the filters."
      operationId: taxes
      security:
        - OAuth2Authentication:
            - 'taxes:r'
    post:
      tags:
        - Taxes
      summary: New F24
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:a`\n\nAdd new F24"
      operationId: taxesAdd
      security:
        - OAuth2Authentication:
            - 'taxes:a'
  '/c/{companyId}/taxes/{documentId}':
    get:
      tags:
        - Taxes
      summary: Get F24 details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: taxesDetails
      security:
        - OAuth2Authentication:
            - 'taxes:r'
    put:
      tags:
        - Taxes
      summary: Edit F24
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:a`\n\nEdit an existing F24 by its unique id."
      operationId: taxesEdit
      security:
        - OAuth2Authentication:
            - 'taxes:a'
    delete:
      tags:
        - Taxes
      summary: Remove a F24
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:a`\n\nDelete an existing document by its unique id."
      operationId: taxesDelete
      security:
        - OAuth2Authentication:
            - 'taxes:a'
  '/c/{companyId}/taxes/attachment':
    post:
      tags:
        - Taxes
      summary: Upload attachment
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:a`\n\nUpload an attachment an return its relative token."
      operationId: taxesAttachment
      security:
        - OAuth2Authentication:
            - 'taxes:a'
  '/c/{companyId}/taxes/{documentId}/attachment':
    delete:
      tags:
        - Taxes
      summary: Remove an attachment
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `taxes:a`\n\nRemove an attachment (but not the F24)"
      operationId: taxesRemoveAttachment
      security:
        - OAuth2Authentication:
            - 'taxes:a'
  '/c/{companyId}/cashbook':
    get:
      tags:
        - Cashbook
      summary: List and search cashbook entries
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:r` \\\n\nGet a list of cashbook notes that match the filters."
      operationId: cashbookList
      security:
        - OAuth2Authentication:
            - 'cashbook:r'
    post:
      tags:
        - Cashbook
      summary: New cashbook entry
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nCreate a new cashbook entry. It is possible to create an entry as an income or an outcome."
      operationId: cashbookCreate
      security:
        - OAuth2Authentication:
            - 'cashbook:a'
      x-private: true
  '/c/{companyId}/cashbook/{documentId}':
    get:
      tags:
        - Cashbook
      summary: Get cashbook entry details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: cashbookDetails
      security:
        - OAuth2Authentication:
            - 'cashbook:r'
      x-private: true
    put:
      tags:
        - Cashbook
      summary: Edit cashbook entry
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nEdit an existing cashbook entry by its unique id."
      operationId: cashbookEdit
      security:
        - OAuth2Authentication:
            - 'cashbook:a'
      x-private: true
    delete:
      tags:
        - Cashbook
      summary: Remove a cashbook entry
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nDelete an existing cashbook entry by its unique id."
      operationId: cashbookDelete
      security:
        - OAuth2Authentication:
            - 'cashbook:a'
      x-private: true
  '/c/{companyId}/receipts':
    get:
      tags:
        - Receipts
      summary: List and search documents
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:r` \\\n\U0001F50D Filtering: `date`, `type`, `description`, `rc_center`, `created_at`, `updated_at` \\\n↕️ Sorting: `date`, `rc_center`, `created_at`, `updated_at` \\\n\U0001F4C4 Paginated results \\\n\U0001F3A9 Customized responses supported\n\nGet a list of receipt documents that match the filters."
      operationId: receipt
      security:
        - OAuth2Authentication:
            - 'receipts:r'
    post:
      tags:
        - Receipts
      summary: New receipt
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:a`\n\nCreate a new receipt."
      operationId: receiptCreate
      security:
        - OAuth2Authentication:
            - 'receipts:a'
  '/c/{companyId}/receipts/{documentId}':
    get:
      tags:
        - Receipts
      summary: Get receipt details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: receiptsDetails
      security:
        - OAuth2Authentication:
            - 'receipts:r'
    put:
      tags:
        - Receipts
      summary: Edit receipt
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:a`\n\nEdit an existing document by its unique id."
      operationId: receiptsEdit
      security:
        - OAuth2Authentication:
            - 'receipts:a'
    delete:
      tags:
        - Receipts
      summary: Remove a receipt
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:a`\n\nDelete an existing document by its unique id."
      operationId: receiptsDelete
      security:
        - OAuth2Authentication:
            - 'receipts:a'
  '/c/{companyId}/receipts/info':
    get:
      tags:
        - Receipts
      summary: Pre-create info
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `receipts:r`\n\nGet the info needed for the document creation flow."
      operationId: receiptsInfo
      security:
        - OAuth2Authentication:
            - 'receipts:r'
  '/c/{companyId}/archive':
    get:
      tags:
        - Archive
      summary: List and search archive document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:r` \\\n\U0001F50D Filtering: `date`, `category`, `description` \\\n↕️ Sorting: `date`, `category`, `description` \\\n\U0001F4C4 Paginated results \\\n\U0001F3A9 Customized responses supported\n\nGet a list of documents in the archive that match the filters."
      operationId: archiveList
      security:
        - OAuth2Authentication:
            - 'archive:r'
    post:
      tags:
        - Archive
      summary: New document to be stored
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:a`\n\nAdd a new document into archive"
      operationId: archiveCreateDocument
      security:
        - OAuth2Authentication:
            - 'archive:a'
  '/c/{companyId}/archive/{documentId}':
    get:
      tags:
        - Archive
      summary: Get archive document details
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      operationId: archiveDetails
      security:
        - OAuth2Authentication:
            - 'archive:r'
    put:
      tags:
        - Archive
      summary: Edit archive document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:a`\n\nEdit an existing document"
      operationId: archiveEdit
      security:
        - OAuth2Authentication:
            - 'archive:a'
    delete:
      tags:
        - Archive
      summary: Remove a archive document
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:a`\n\nDelete an existing document by its unique id."
      operationId: archiveDelete
      security:
        - OAuth2Authentication:
            - 'archive:a'
  '/c/{companyId}/archive/attachment':
    post:
      tags:
        - Archive
      summary: Upload attachment
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `archive:a`\n\nUpload an attachment to a document into archive section"
      operationId: archiveAttachment
      security:
        - OAuth2Authentication:
            - 'archive:a'
  /info/countries:
    get:
      tags:
        - Info
      summary: Get the countries list
      description: Get the list of the countries supported by entities and documents.
      operationId: infoCountries
      security:
        - OAuth2Authentication:
            - no scope required
  /info/cities:
    get:
      tags:
        - Info
      summary: Get the cities list
      description: Get the list of the Italian cities.
      operationId: infoCities
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/vat_types':
    get:
      tags:
        - Info
      summary: Vat types list
      description: "\U0001F465 Company context\n\U0001F512 Required scope: `settings:r` \\\n\U0001F3A9 Customized responses supported\n\nGet the list of the available vat types."
      operationId: infoVatTypes
      security:
        - OAuth2Authentication:
            - 'settings:r'
  /info/languages:
    get:
      tags:
        - Info
      summary: Get the languages list
      description: Get the list of the supported languages.
      operationId: infoLanguages
      security:
        - OAuth2Authentication:
            - no scope required
  /info/templates:
    get:
      tags:
        - Info
      summary: Get the templates list
      description: |-
        Get the list of the available templates.        
        If a CompanyAuthentication is given, custom templates are included.
      operationId: infoTemplates
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/payment_methods':
    get:
      tags:
        - Info
      summary: Payment methods list
      description: "\U0001F465 Company context \\\n\U0001F3A9 Customized responses supported\n\nGet the list of the available payment methods."
      operationId: infoPaymentMethodsList
      security:
        - OAuth2Authentication:
            - no scope required
      x-internal: false
  '/c/{companyId}/info/payment_accounts':
    get:
      tags:
        - Info
      summary: Payment accounts list
      description: "\U0001F465 Company context \\\n\U0001F3A9 Customized responses supported\n\nGet the list of the available payment accounts."
      operationId: infoPaymentAccountsList
      security:
        - OAuth2Authentication:
            - no scope required
  /info/currencies:
    get:
      tags:
        - Info
      summary: Currencies list
      description: Get the currencies list.
      operationId: currenciesList
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/revenue_centers':
    get:
      tags:
        - Info
      summary: List of the revenue centers
      description: "\U0001F465 Company context\n\nGet the list of the revenue centers"
      operationId: infoRevenuesCenters
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/cost_centers':
    get:
      tags:
        - Info
      summary: List of the cost centers
      description: "\U0001F465 Company context\n\nGet the list of the cost centers"
      operationId: infoCostCenterList
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/product_categories':
    get:
      tags:
        - Info
      summary: Product categories list
      description: "\U0001F465 Company context\n\nGet the product categories list"
      operationId: infoProductscategoriesList
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/received_document_categories':
    get:
      tags:
        - Info
      summary: Received document categories list
      description: "\U0001F465 Company context\n\nGet the received document categories list"
      operationId: infoRecievedDocumentsList
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/info/archive_categories':
    get:
      tags:
        - Info
      summary: Archive categories list
      description: "\U0001F465 Company context\n\nGet the archive categories list"
      operationId: infoArchiveCategoriesList
      security:
        - OAuth2Authentication:
            - no scope required
  /info/dn_causals:
    get:
      tags:
        - Info
      summary: Get the delivery note default causals
      description: Get the delivery note default causals.
      operationId: infoDnCausals
      security:
        - OAuth2Authentication:
            - no scope required
  '/c/{companyId}/issued_documents/{document_id}/e_invoice/xml_verify':
    get:
      tags:
        - Issued e-invoices
      summary: Verify e-invoice xml
      description: "\U0001F465 Company context\n\nVerify e-invoice xml format.\nCheck if all mandatory fields are filled and if all fieldds are in right format."
      operationId: issuedDocumentEinvoiceVerifyXml
      security:
        - OAuth2Authentication:
            - no scope required
components:
  securitySchemes:
    OAuth2Authentication:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api-v2.fattureincloud.it/oauth/authorize'
          tokenUrl: 'https://api-v2.fattureincloud.it/oauth/token'
          scopes:
            'situation:r': ''
            'entity.clients:r': ''
            'entity.clients:a': ''
            'entity.suppliers:r': ''
            'entity.suppliers:a': ''
            'products:r': ''
            'products:a': ''
            'stock:r': ''
            'stock:a': ''
            'issued_documents.invoices:r': ''
            'issued_documents.invoices:a': ''
            'issued_documents.credit_notes:r': ''
            'issued_documents.credit_notes:a': ''
            'issued_documents.quotes:r': ''
            'issued_documents.quotes:a': ''
            'issued_documents.proformas:r': ''
            'issued_documents.proformas:a': ''
            'issued_documents.receipts:r': ''
            'issued_documents.receipts:a': ''
            'issued_documents.delivery_notes:r': ''
            'issued_documents.delivery_notes:a': ''
            'issued_documents.orders:r': ''
            'issued_documents.orders:a': ''
            'issued_documents.work_reports:r': ''
            'issued_documents.work_reports:a': ''
            'issued_documents.supplier_orders:r': ''
            'issued_documents.supplier_orders:a': ''
            'received_documents:r': ''
            'received_documents:a': ''
            'receipts:r': ''
            'receipts:a': ''
            'calendar:r': ''
            'calendar:a': ''
            'archive:r': ''
            'archive:a': ''
            'taxes:r': ''
            'taxes:a': ''
            'emails:r': ''
            'cashbook:r': ''
            'cashbook:a': ''
            'settings:r': ''
            'settings:a': ''
            'issued_documents.[documentType]:r': ''
            'issued_documents.[documentType]:a': ''
            no scope required: ''
