openapi: 3.0.0
info:
  title: Fatture in Cloud API v2 - API Reference
  description: "## Request informations\nIn every request description you will be able to find some additional informations about context, permissions and supported functionality:\n\n| Parameter | Description |\n|-----------|-------------|\n| \U0001F465 Context | Indicate the subject of the request. Can be `company`, `user` or `accountant`.  |\n| \U0001F512 Required scope | If present, indicates the required scope to fulfill the request. |\n| \U0001F50D Filtering | If present, indicates which fi[...]"
  contact:
    name: Fatture in Cloud
    url: 'https://www.fattureincloud.it'
    email: info@fattureincloud.it
  license:
    name: ''
    url: 'https://www.fattureincloud.it'
  version: v1.0.1
servers:
  - url: 'https://api-v2.fattureincloud.it'
tags:
  - name: Archive
  - name: Cashbook
  - name: Clients
  - name: Companies
  - name: Info
  - name: Issued Documents
  - name: Issued e-invoices
  - name: Products
  - name: Receipts
  - name: Received Documents
  - name: Suppliers
  - name: Taxes
  - name: User
paths:
  /user/info:
    get:
      tags:
        - User
      summary: Get user info
      operationId: userInfo
      description: "Makes possible to retrieve the current user's info.\n\n\U0001F464 Person context\n\nGet user email, name and id."
      security:
        - OAuth2AuthenticationCodeFlow: []
  /user/companies:
    get:
      summary: userCompanies
      tags:
        - User
      operationId: userCompanies
      description: "\U0001F464 Person context\n\nGet a list of the controlled companies and their CompanyAuthentication tokens."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/company/info':
    get:
      summary: Get Company Info
      operationId: getCompanyInfo
      description: 'Get company info like email, license expire date and access info for each document and section'
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Companies
  '/c/{company_id}/entities/clients':
    get:
      summary: List Clients
      tags:
        - Clients
      operationId: listClients
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:r\n\U0001F50D Filtering: id, code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes, imported, atoka_show, e_invoice, ei_code, created_at, updated_at\n↕️ Sorting: code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, [...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:r'
    post:
      summary: Create Client
      operationId: createClient
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.clients:a`\n\nCreate a new client."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
  '/c/{company_id}/entities/suppliers':
    get:
      summary: List Suppliers
      operationId: listSuppliers
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:r\n\U0001F50D Filtering: id, code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes, imported, atoka_show, created_at, updated_at\n↕️ Sorting: code, name, type, vat_number, tax_code, address_street, address_postal_code, address_city, address_province, country, email, certified_email, phone, fax, notes,[...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:r'
      tags:
        - Suppliers
    post:
      summary: Create Supplier
      operationId: createSupplier
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `entity.suppliers:a`\n\nCreate a new supplier."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
  '/c/{company_id}/entities/clients/{client_id}':
    get:
      summary: Get Client
      tags:
        - Clients
      operationId: getClient
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:r'
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing client by its unique id."
    put:
      summary: Modify Client
      operationId: modifyClient
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:a\n\nEdit an existing client by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
    delete:
      summary: Delete Client
      operationId: deleteClient
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.clients:a\n\nDelete an existing client by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.clients:a'
      tags:
        - Clients
  '/c/{company_id}/entities/suppliers/{supplier_id}':
    get:
      summary: Get Supplier
      operationId: getSupplier
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:r'
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing supplier by its unique id."
      tags:
        - Suppliers
    put:
      summary: Modify Supplier
      operationId: modifySupplier
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:a\n\nEdit an existing supplier by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
    delete:
      summary: Delete Supplier
      operationId: deleteSupplier
      description: "\U0001F465 Company context\n\U0001F512 Required scope: entity.suppliers:a\n\nDelete an existing supplier by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'entity.suppliers:a'
      tags:
        - Suppliers
  '/c/{company_id}/products':
    get:
      summary: List Products
      tags:
        - Products
      operationId: listProducts
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:r\n\U0001F50D Filtering: id, name, code, net_price, gross_price, net_cost, description, category, notes, in_stock, created_at, updated_at\n↕️ Sorting: name, code, net_price, gross_price, net_cost, description, category, notes, in_stock, created_at, updated_at\n\U0001F4C4 Paginated results\n\U0001F3A9 Customized responses supported\n\nGet a list of products that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:r'
    post:
      summary: ''
      operationId: createProduct
      tags:
        - Products
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:a\n\nCreate a new product."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
  '/c/{company_id}/products/{product_id}':
    get:
      summary: Get Product
      tags:
        - Products
      operationId: getProduct
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:r\n\U0001F3A9 Customized responses supported\n\nGet product details"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:r'
    put:
      summary: Modify Product
      operationId: modifyProduct
      description: "\U0001F465 Company context\n\U0001F512 Required scope: products:a\n\nEdit an existing product by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
      tags:
        - Products
    delete:
      summary: ''
      operationId: deleteProduct
      description: Delete Product
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'products:a'
      tags:
        - Products
  '/c/{company_id}/issued_documents':
    get:
      summary: List Issued Documents
      tags:
        - Issued Documents
      operationId: listIssuedDocuments
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:r\n\U0001F50D Filtering: type, entity.id, entity.name, entity.vat_number, entity.tax_code, entity.city, entity.province, entity.country, date, number, numeration, any_subject, amount_net, amount_vat, amount_gross, next_due_date, created_at, updated_at\n↕️ Sorting: entity.id, entity.name, entity.vat_number, entity.tax_code, entity.city, entity.province, entity.country, date, number, numerati[...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:r'
            - 'issued_documents.credit_note:r'
            - 'issued_documents.receipt:r'
            - 'issued_documents.order:r'
            - 'issued_documents.quote:r'
            - 'issued_documents.proforma:r'
            - 'issued_documents.delivery_note:r'
    post:
      summary: Create Issued Document
      operationId: createIssuedDocument
      tags:
        - Issued Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:a\n\nCreate a new document."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:a'
            - 'issued_documents.credit_note:a'
            - 'issued_documents.receipt:a'
            - 'issued_documents.order:a'
            - 'issued_documents.quote:a'
            - 'issued_documents.proforma:a'
            - 'issued_documents.delivery_note:a'
  '/c/{company_id}/issued_documents/{document_id}':
    get:
      summary: Get Issued Document
      tags:
        - Issued Documents
      operationId: getIssuedDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id.\n\n"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:r'
            - 'issued_documents.credit_note:r'
            - 'issued_documents.receipt:r'
            - 'issued_documents.order:r'
            - 'issued_documents.quote:r'
            - 'issued_documents.proforma:r'
            - 'issued_documents.delivery_note:r'
    put:
      summary: Modify Issued Document
      operationId: modifyIssuedDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:a\n\nEdit an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:a'
            - 'issued_documents.credit_note:a'
            - 'issued_documents.receipt:a'
            - 'issued_documents.order:a'
            - 'issued_documents.quote:a'
            - 'issued_documents.proforma:a'
            - 'issued_documents.delivery_note:a'
      tags:
        - Issued Documents
    delete:
      summary: Delete Issued Document
      operationId: deleteIssuedDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:a\n\nDelete an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:a'
            - 'issued_documents.credit_note:a'
            - 'issued_documents.receipt:a'
            - 'issued_documents.order:a'
            - 'issued_documents.quote:a'
            - 'issued_documents.proforma:a'
            - 'issued_documents.delivery_note:a'
      tags:
        - Issued Documents
  '/c/{company_id}/issued_documents/totals':
    post:
      summary: Get New Issued Document Totals
      operationId: getNewIssuedDocumentTotals
      description: "\U0001F465 Company context\n\nGet the totals of a document"
      tags:
        - Issued Documents
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/issued_documents/{document_id}/totals':
    post:
      summary: Get Existing Issued Document Totals
      operationId: getExistingIssuedDocumentTotals
      tags:
        - Issued Documents
      description: "\U0001F465 Company context\n\nGet existing document totals"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/issued_documents/attachment':
    post:
      summary: Upload Issued Document Attachment
      operationId: uploadIssuedDocumentAttachment
      tags:
        - Issued Documents
      description: "\U0001F465 Company context\n\nUpload an attachment to an issued document"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/issued_documents/info':
    get:
      summary: Get Issued Document Pre-create info
      tags:
        - Issued Documents
      operationId: getIssuedDocumentPreCreateInfo
      description: "\U0001F465 Company context\n\nGet the info needed for the document creation flow."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/issued_documents/{document_id}/attachment':
    delete:
      summary: Delete Issued Document Attachment
      operationId: deleteIssuedDocumentAttachment
      description: "\U0001F465 Company context\n\nRemove the attachment (but not the document)"
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Issued Documents
  '/c/{company_id}/issued_documents/{document_id}/email':
    get:
      summary: Get Email Data
      tags:
        - Issued Documents
      operationId: getEmailData
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:r\n\nGet pre-compiled email data like subject, body, attachments, SMTP credentials, CC, recipients list."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:r'
            - 'issued_documents.credit_note:r'
            - 'issued_documents.receipt:r'
            - 'issued_documents.order:r'
            - 'issued_documents.quote:r'
            - 'issued_documents.proforma:r'
            - 'issued_documents.delivery_note:r'
    post:
      summary: Schedule Email
      operationId: scheduleEmail
      description: "\U0001F465 Company context\n\U0001F512 Required scope: issued_documents.[documentType]:r\n\nSchedule email sending of a document."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'issued_documents.invoice:r'
            - 'issued_documents.credit_note:r'
            - 'issued_documents.receipt:r'
            - 'issued_documents.order:r'
            - 'issued_documents.quote:r'
            - 'issued_documents.proforma:r'
            - 'issued_documents.delivery_note:r'
      tags:
        - Issued Documents
  '/c/{company_id}/issued_documents/{document_id}/e_invoice/send':
    post:
      summary: Send the e-invoice
      operationId: sendEInvoice
      description: "\U0001F465 Company context\n\nSend the e-invoice to SDI"
      security:
        - OAuth2AuthenticationCodeFlow: []
      tags:
        - Issued e-invoices
  '/c/{company_id}/issued_documents/{document_id}/e_invoice/xml_verify':
    get:
      summary: Verify e-invoice xml
      tags:
        - Issued e-invoices
      operationId: verifyEInvoiceXml
      description: "\U0001F465 Company context\n\nVerify e-invoice xml format. Check if all mandatory fields are filled and if all fields are in right format."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/received_documents':
    get:
      summary: List Received Documents
      tags:
        - Received Documents
      operationId: listReceivedDocuments
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:r (but if the document is a passive_delivery_note you’ll need stock:r scope)\n\U0001F50D Filtering: id, type, category, description, entity.id, entity.name, date, next_due_date, amount_gross, amount_net, amount_vat, invoice_number, created_at, updated_at\n↕️ Sorting: id, category, entity.id, entity.name, date, next_due_date, amount_gross, amount_net, amount_vat, created_at, updated_at\n\U0001F4C4 Pagina[...]"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:r'
            - 'stock:r'
    post:
      summary: Create Received Document
      operationId: createReceivedDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nCreate a new received document."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
      tags:
        - Received Documents
  '/c/{company_id}/received_documents/{document_id}':
    get:
      summary: Get Received Document
      tags:
        - Received Documents
      operationId: getReceivedDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:r (but if the document is a passive_delivery_note you’ll need stock:r scope)\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:r'
            - 'stock:r'
    put:
      summary: Modify Received Document
      operationId: modifyReceivedDocument
      tags:
        - Received Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nEdit an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
    delete:
      summary: ''
      operationId: deleteReceivedDocument
      tags:
        - Received Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nDelete an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
  '/c/{company_id}/received_documents/totals':
    post:
      summary: Get New Received Document Totals
      operationId: getNewReceivedDocumentTotals
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nCalculate totals of the received document passed in the body."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
      tags:
        - Received Documents
  '/c/{company_id}/received_documents/{document_id}/totals':
    post:
      summary: Get Existing Received Document Totals
      operationId: getExistingReceivedDocumentTotals
      tags:
        - Received Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nCalculate totals of the received document indicated by the id with the changes passed in the body."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
  '/c/{company_id}/received_documents/attachment':
    post:
      summary: Upload Received Document Attachment
      operationId: uploadReceivedDocumentAttachment
      tags:
        - Received Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nUpload an attachment and return the relative token."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
  '/c/{company_id}/received_documents/{document_id}/attachment':
    delete:
      summary: Delete Received Document Attachment
      operationId: deleteReceivedDocumentAttachment
      tags:
        - Received Documents
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:a (but if the document is a passive_delivery_note you’ll need stock:a scope)\n\nRemove the attachment (but not the document)"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:a'
            - 'stock:a'
  '/c/{company_id}/received_documents/info':
    get:
      summary: Get Received Document Pre-Create Info
      tags:
        - Received Documents
      operationId: getReceivedDocumentPreCreateInfo
      description: "\U0001F465 Company context\n\U0001F512 Required scope: received_documents:r\n\nGet the info needed for the document creation flow."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'received_documents:r'
  '/c/{company_id}/receipts':
    get:
      summary: List Receipts
      tags:
        - Receipts
      operationId: listReceipts
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:r\n\U0001F50D Filtering: date, type, description, rc_center, created_at, updated_at\n↕️ Sorting: date, rc_center, created_at, updated_at\n\U0001F4C4 Paginated results\n\U0001F3A9 Customized responses supported\n\nGet a list of receipt documents that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:r'
    post:
      summary: Create Receipt
      operationId: createReceipt
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:a\n\nCreate a new receipt."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:a'
      tags:
        - Receipts
  '/c/{company_id}/receipts/{document_id}':
    get:
      summary: Get Receipt
      tags:
        - Receipts
      operationId: getReceipt
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:r'
    put:
      summary: Modify Receipt
      operationId: modifyReceipt
      tags:
        - Receipts
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:a\n\nEdit an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:a'
    delete:
      summary: Delete Receipt
      operationId: deleteReceipt
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:a\n\nDelete an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:a'
      tags:
        - Receipts
  '/c/{company_id}/receipts/info':
    get:
      summary: Get Receipt Pre-Create Info
      tags:
        - Receipts
      operationId: getReceiptPreCreateInfo
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:r\n\nGet the info needed for the document creation flow."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:r'
  '/c/{company_id}/receipts/monthly_totals':
    get:
      summary: Get Receipts Monthly Totals
      tags:
        - Receipts
      operationId: getReceiptsMonthlyTotals
      description: "\U0001F465 Company context\n\U0001F512 Required scope: receipts:r\n\nGet the monthly totals by year and receipt type."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'receipts:r'
  '/c/{company_id}/taxes':
    get:
      summary: List F24
      tags:
        - Taxes
      operationId: listF24
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:r\n\U0001F50D Filtering: due_date, status, amount, description\n↕️ Sorting: due_date, status, amount, description\n\U0001F4C4 Paginated results\n\U0001F3A9 Customized responses supported\n\nGet a list of F24 that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:r'
    post:
      summary: Create F24
      operationId: createF24
      tags:
        - Taxes
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:a\n\nAdd new F24"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:a'
  '/c/{company_id}/taxes/{document_id}':
    get:
      summary: Get F24
      tags:
        - Taxes
      operationId: getF24
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing F24 document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:r'
    put:
      summary: Modify F24
      operationId: modifyF24
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:a\n\nEdit an existing F24 by its unique id."
      tags:
        - Taxes
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:a'
    delete:
      summary: Delete F24
      operationId: deleteF24
      tags:
        - Taxes
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:a\n\nDelete an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:a'
  '/c/{company_id}/taxes/attachment':
    post:
      summary: Upload F24 Attachment
      tags:
        - Taxes
      operationId: uploadF24Attachment
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:a\n\nUpload an attachment an return its relative token."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:a'
  '/c/{company_id}/taxes/{document_id}/attachment':
    delete:
      summary: Delete F24 Attachment
      tags:
        - Taxes
      operationId: deleteF24Attachment
      description: "\U0001F465 Company context\n\U0001F512 Required scope: taxes:a\n\nRemove an attachment (but not the F24)"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'taxes:a'
  '/c/{company_id}/archive':
    get:
      summary: List Archive Documents
      tags:
        - Archive
      operationId: listArchiveDocuments
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:r\n\U0001F50D Filtering: date, category, description\n↕️ Sorting: date, category, description\n\U0001F4C4 Paginated results\n\U0001F3A9 Customized responses supported\n\nGet a list of documents in the archive that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:r'
    post:
      summary: Create Archive Document
      operationId: createArchiveDocument
      tags:
        - Archive
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:a\n\nAdd a new document into archive"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:a'
  '/c/{company_id}/archive/{document_id}':
    get:
      summary: Get Archive Document
      tags:
        - Archive
      operationId: getArchiveDocument
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:r\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:r'
    put:
      summary: Modify Archive Document
      operationId: modifyArchiveDocument
      tags:
        - Archive
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:a\n\nEdit an existing document"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:a'
    delete:
      summary: Delete Archive Document
      operationId: deleteArchiveDocument
      tags:
        - Archive
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:a\n\nDelete an existing document by its unique id.\n\n"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:a'
  '/c/{company_id}/archive/attachment':
    post:
      summary: Upload Archive Document Attachment
      tags:
        - Archive
      operationId: uploadArchiveDocumentAttachment
      description: "\U0001F465 Company context\n\U0001F512 Required scope: archive:a\n\nUpload an attachment to a document into archive section"
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'archive:a'
  '/c/{company_id}/cashbook':
    get:
      summary: List Cashbook Entries
      tags:
        - Cashbook
      operationId: listCashbookEntries
      description: "\U0001F465 Company context\n\U0001F512 Required scope: cashbook:r \\\n\nGet a list of cashbook notes that match the filters."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'cashbook:r'
    post:
      summary: Create Cashbook Entry
      operationId: createCashbookEntry
      tags:
        - Cashbook
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nCreate a new cashbook entry. It is possible to create an entry as an income or an outcome."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'cashbook:a'
  '/c/{company_id}/cashbook/{document_id}':
    get:
      summary: Get Cashbook Entry
      tags:
        - Cashbook
      operationId: getCashbookEntry
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:r` \\\n\U0001F3A9 Customized responses supported\n\nGet details of an existing document by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'cashbook:r'
    put:
      summary: Modify Cashbook Entry
      operationId: modifyCashbookEntry
      tags:
        - Cashbook
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nEdit an existing cashbook entry by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'cashbook:a'
    delete:
      summary: Delete Cashbook Entry
      operationId: deleteCashbookEntry
      description: "\U0001F465 Company context \\\n\U0001F512 Required scope: `cashbook:a`\n\nDelete an existing cashbook entry by its unique id."
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'cashbook:a'
      tags:
        - Cashbook
  /info/countries:
    get:
      summary: List Countries
      tags:
        - Info
      operationId: List Countries
      description: Get the list of the countries supported by entities and documents.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/cities:
    get:
      summary: List Cities
      tags:
        - Info
      operationId: listCities
      description: Get the list of the Italian cities.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/languages:
    get:
      summary: List Languages
      tags:
        - Info
      operationId: listLanguages
      description: Get the list of the supported languages.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/templates:
    get:
      summary: List Templates
      tags:
        - Info
      operationId: listTemplates
      description: |-
        Get the list of the available templates.
        If a CompanyAuthentication is given, custom templates are included.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/currencies:
    get:
      summary: List Currencies
      tags:
        - Info
      operationId: listCurrencies
      description: Get the currencies list.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/measures:
    get:
      summary: List Units of Measure
      tags:
        - Info
      operationId: listUnitsOfMeasure
      description: Get a list of the units of measure.
      security:
        - OAuth2AuthenticationCodeFlow: []
  /info/dn_causals:
    get:
      summary: List Delivery Notes Default Causals
      tags:
        - Info
      operationId: listDeliveryNotesDefaultCausals
      description: Get the delivery note default causals.
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/vat_types':
    get:
      summary: List Vat Types
      tags:
        - Info
      operationId: listVatTypes
      security:
        - OAuth2AuthenticationCodeFlow:
            - 'settings:r'
      description: "\U0001F465 Company context \U0001F512 Required scope: settings:r\n\U0001F3A9 Customized responses supported\n\nGet the list of the available vat types."
  '/c/{company_id}/info/payment_methods':
    get:
      summary: List Payment Methods
      tags:
        - Info
      operationId: listPaymentMethods
      description: "\U0001F465 Company context\n\U0001F3A9 Customized responses supported\n\nGet the list of the available payment methods."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/payment_accounts':
    get:
      summary: List Payment Accounts
      tags:
        - Info
      operationId: listPaymentAccounts
      description: "\U0001F465 Company context\n\U0001F3A9 Customized responses supported\n\nGet the list of the available payment accounts."
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/revenue_centers':
    get:
      summary: List Revenue Centers
      tags:
        - Info
      operationId: listRevenueCenters
      description: "\U0001F465 Company context\n\nGet a list of the revenue centers"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/cost_centers':
    get:
      summary: List Cost Centers
      tags:
        - Info
      operationId: listCostCenters
      description: "\U0001F465 Company context\n\nGet a list of the cost centers"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/product_categories':
    get:
      summary: List Product Categories
      tags:
        - Info
      operationId: listProductCategories
      description: "\U0001F465 Company context\n\nGet the product categories list"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/received_document_categories':
    get:
      summary: List Received Document Categories List
      tags:
        - Info
      operationId: listReceivedDocumentCategories
      description: "\U0001F465 Company context\n\nGet the received document categories list"
      security:
        - OAuth2AuthenticationCodeFlow: []
  '/c/{company_id}/info/archive_categories':
    get:
      summary: List Archive Categories
      tags:
        - Info
      operationId: listArchiveCategories
      description: "\U0001F465 Company context\n\nGet the archive categories list"
      security:
        - OAuth2AuthenticationCodeFlow: []
components:
  securitySchemes:
    OAuth2AuthenticationCodeFlow:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: 'https://api-v2.fattureincloud.it/oauth/token'
          refreshUrl: ''
          scopes:
            'entity.clients:r': ''
            'entity.clients:a': ''
            'entity.suppliers:r': ''
            'entity.suppliers:a': ''
            'products:r': ''
            'products:a': ''
            'issued_documents.invoice:r': ''
            'issued_documents.credit_note:r': ''
            'issued_documents.receipt:r': ''
            'issued_documents.order:r': ''
            'issued_documents.quote:r': ''
            'issued_documents.proforma:r': ''
            'issued_documents.delivery_note:r': ''
            'issued_documents.invoice:a': ''
            'issued_documents.credit_note:a': ''
            'issued_documents.receipt:a': ''
            'issued_documents.order:a': ''
            'issued_documents.quote:a': ''
            'issued_documents.proforma:a': ''
            'issued_documents.delivery_note:a': ''
            'received_documents:r': ''
            'received_documents:a': ''
            'stock:r': ''
            'stock:a': ''
            'receipts:r': ''
            'receipts:a': ''
            'taxes:r': ''
            'taxes:a': ''
            'archive:r': ''
            'archive:a': ''
            'cashbook:r': ''
            'cashbook:a': ''
            'settings:r': ''
            'settings:a': ''
          authorizationUrl: 'https://api-v2.fattureincloud.it/oauth/authorize'
security:
  - OAuth2AuthenticationCodeFlow: []
