/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.CompanyInfoAccessInfo;
import it.fattureincloud.sdk.model.CompanyInfoPlanInfo;
import it.fattureincloud.sdk.model.CompanyType;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CompanyInfo
 */
public class CompanyInfoTest {
    private final CompanyInfo model = new CompanyInfo();

    /**
     * Model tests for CompanyInfo
     */
    @Test
    public void testCompanyInfo() {
        // TODO: test CompanyInfo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'accessInfo'
     */
    @Test
    public void accessInfoTest() {
        // TODO: test accessInfo
    }

    /**
     * Test the property 'planInfo'
     */
    @Test
    public void planInfoTest() {
        // TODO: test planInfo
    }

    /**
     * Test the property 'accountantId'
     */
    @Test
    public void accountantIdTest() {
        // TODO: test accountantId
    }

    /**
     * Test the property 'isAccountant'
     */
    @Test
    public void isAccountantTest() {
        // TODO: test isAccountant
    }

}
