/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.EmailDataDefaultSenderEmail;
import it.fattureincloud.sdk.model.SenderEmail;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EmailData
 */
public class EmailDataTest {
    private final EmailData model = new EmailData();

    /**
     * Model tests for EmailData
     */
    @Test
    public void testEmailData() {
        // TODO: test EmailData
    }

    /**
     * Test the property 'recipientEmail'
     */
    @Test
    public void recipientEmailTest() {
        // TODO: test recipientEmail
    }

    /**
     * Test the property 'defaultSenderEmail'
     */
    @Test
    public void defaultSenderEmailTest() {
        // TODO: test defaultSenderEmail
    }

    /**
     * Test the property 'senderEmailsList'
     */
    @Test
    public void senderEmailsListTest() {
        // TODO: test senderEmailsList
    }

    /**
     * Test the property 'ccEmail'
     */
    @Test
    public void ccEmailTest() {
        // TODO: test ccEmail
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'documentExists'
     */
    @Test
    public void documentExistsTest() {
        // TODO: test documentExists
    }

    /**
     * Test the property 'deliveryNoteExists'
     */
    @Test
    public void deliveryNoteExistsTest() {
        // TODO: test deliveryNoteExists
    }

    /**
     * Test the property 'attachmentExists'
     */
    @Test
    public void attachmentExistsTest() {
        // TODO: test attachmentExists
    }

    /**
     * Test the property 'accompanyingInvoiceExists'
     */
    @Test
    public void accompanyingInvoiceExistsTest() {
        // TODO: test accompanyingInvoiceExists
    }

    /**
     * Test the property 'defaultAttachPdf'
     */
    @Test
    public void defaultAttachPdfTest() {
        // TODO: test defaultAttachPdf
    }

}
