/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.VatType;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IssuedDocumentItemsListItem
 */
public class IssuedDocumentItemsListItemTest {
    private final IssuedDocumentItemsListItem model = new IssuedDocumentItemsListItem();

    /**
     * Model tests for IssuedDocumentItemsListItem
     */
    @Test
    public void testIssuedDocumentItemsListItem() {
        // TODO: test IssuedDocumentItemsListItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'qty'
     */
    @Test
    public void qtyTest() {
        // TODO: test qty
    }

    /**
     * Test the property 'measure'
     */
    @Test
    public void measureTest() {
        // TODO: test measure
    }

    /**
     * Test the property 'netPrice'
     */
    @Test
    public void netPriceTest() {
        // TODO: test netPrice
    }

    /**
     * Test the property 'grossPrice'
     */
    @Test
    public void grossPriceTest() {
        // TODO: test grossPrice
    }

    /**
     * Test the property 'vat'
     */
    @Test
    public void vatTest() {
        // TODO: test vat
    }

    /**
     * Test the property 'notTaxable'
     */
    @Test
    public void notTaxableTest() {
        // TODO: test notTaxable
    }

    /**
     * Test the property 'applyWithholdingTaxes'
     */
    @Test
    public void applyWithholdingTaxesTest() {
        // TODO: test applyWithholdingTaxes
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'discountHighlight'
     */
    @Test
    public void discountHighlightTest() {
        // TODO: test discountHighlight
    }

    /**
     * Test the property 'inDdt'
     */
    @Test
    public void inDdtTest() {
        // TODO: test inDdt
    }

    /**
     * Test the property 'stock'
     */
    @Test
    public void stockTest() {
        // TODO: test stock
    }

    /**
     * Test the property 'eiRaw'
     */
    @Test
    public void eiRawTest() {
        // TODO: test eiRaw
    }

}
