/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.IssuedDocument;
import it.fattureincloud.sdk.model.ListIssuedDocumentsResponsePage;
import it.fattureincloud.sdk.model.Pagination;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListIssuedDocumentsResponse
 */
public class ListIssuedDocumentsResponseTest {
    private final ListIssuedDocumentsResponse model = new ListIssuedDocumentsResponse();

    /**
     * Model tests for ListIssuedDocumentsResponse
     */
    @Test
    public void testListIssuedDocumentsResponse() {
        // TODO: test ListIssuedDocumentsResponse
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'firstPageUrl'
     */
    @Test
    public void firstPageUrlTest() {
        // TODO: test firstPageUrl
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'lastPage'
     */
    @Test
    public void lastPageTest() {
        // TODO: test lastPage
    }

    /**
     * Test the property 'lastPageUrl'
     */
    @Test
    public void lastPageUrlTest() {
        // TODO: test lastPageUrl
    }

    /**
     * Test the property 'nextPageUrl'
     */
    @Test
    public void nextPageUrlTest() {
        // TODO: test nextPageUrl
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'perPage'
     */
    @Test
    public void perPageTest() {
        // TODO: test perPage
    }

    /**
     * Test the property 'prevPageUrl'
     */
    @Test
    public void prevPageUrlTest() {
        // TODO: test prevPageUrl
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
