/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import it.fattureincloud.sdk.model.PermissionLevel;
import it.fattureincloud.sdk.model.PermissionsFicIssuedDocumentsDetailed;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Permissions
 */
public class PermissionsTest {
    private final Permissions model = new Permissions();

    /**
     * Model tests for Permissions
     */
    @Test
    public void testPermissions() {
        // TODO: test Permissions
    }

    /**
     * Test the property 'ficSituation'
     */
    @Test
    public void ficSituationTest() {
        // TODO: test ficSituation
    }

    /**
     * Test the property 'ficClients'
     */
    @Test
    public void ficClientsTest() {
        // TODO: test ficClients
    }

    /**
     * Test the property 'ficSuppliers'
     */
    @Test
    public void ficSuppliersTest() {
        // TODO: test ficSuppliers
    }

    /**
     * Test the property 'ficProducts'
     */
    @Test
    public void ficProductsTest() {
        // TODO: test ficProducts
    }

    /**
     * Test the property 'ficIssuedDocuments'
     */
    @Test
    public void ficIssuedDocumentsTest() {
        // TODO: test ficIssuedDocuments
    }

    /**
     * Test the property 'ficReceivedDocuments'
     */
    @Test
    public void ficReceivedDocumentsTest() {
        // TODO: test ficReceivedDocuments
    }

    /**
     * Test the property 'ficReceipts'
     */
    @Test
    public void ficReceiptsTest() {
        // TODO: test ficReceipts
    }

    /**
     * Test the property 'ficCalendar'
     */
    @Test
    public void ficCalendarTest() {
        // TODO: test ficCalendar
    }

    /**
     * Test the property 'ficArchive'
     */
    @Test
    public void ficArchiveTest() {
        // TODO: test ficArchive
    }

    /**
     * Test the property 'ficTaxes'
     */
    @Test
    public void ficTaxesTest() {
        // TODO: test ficTaxes
    }

    /**
     * Test the property 'ficStock'
     */
    @Test
    public void ficStockTest() {
        // TODO: test ficStock
    }

    /**
     * Test the property 'ficCashbook'
     */
    @Test
    public void ficCashbookTest() {
        // TODO: test ficCashbook
    }

    /**
     * Test the property 'ficSettings'
     */
    @Test
    public void ficSettingsTest() {
        // TODO: test ficSettings
    }

    /**
     * Test the property 'ficEmails'
     */
    @Test
    public void ficEmailsTest() {
        // TODO: test ficEmails
    }

    /**
     * Test the property 'ficExport'
     */
    @Test
    public void ficExportTest() {
        // TODO: test ficExport
    }

    /**
     * Test the property 'ficImportBankstatements'
     */
    @Test
    public void ficImportBankstatementsTest() {
        // TODO: test ficImportBankstatements
    }

    /**
     * Test the property 'ficImportClientsSuppliers'
     */
    @Test
    public void ficImportClientsSuppliersTest() {
        // TODO: test ficImportClientsSuppliers
    }

    /**
     * Test the property 'ficImportIssuedDocuments'
     */
    @Test
    public void ficImportIssuedDocumentsTest() {
        // TODO: test ficImportIssuedDocuments
    }

    /**
     * Test the property 'ficImportProducts'
     */
    @Test
    public void ficImportProductsTest() {
        // TODO: test ficImportProducts
    }

    /**
     * Test the property 'ficRecurring'
     */
    @Test
    public void ficRecurringTest() {
        // TODO: test ficRecurring
    }

    /**
     * Test the property 'ficRiba'
     */
    @Test
    public void ficRibaTest() {
        // TODO: test ficRiba
    }

    /**
     * Test the property 'dicEmployees'
     */
    @Test
    public void dicEmployeesTest() {
        // TODO: test dicEmployees
    }

    /**
     * Test the property 'dicSettings'
     */
    @Test
    public void dicSettingsTest() {
        // TODO: test dicSettings
    }

    /**
     * Test the property 'dicTimesheet'
     */
    @Test
    public void dicTimesheetTest() {
        // TODO: test dicTimesheet
    }

    /**
     * Test the property 'ficIssuedDocumentsDetailed'
     */
    @Test
    public void ficIssuedDocumentsDetailedTest() {
        // TODO: test ficIssuedDocumentsDetailed
    }

}
