type: object
properties:
  id:
    type: integer
    description: Unique identifier.
    nullable: true
  name:
    type: string
    description: Product name.
    nullable: true
  code:
    type: string
    nullable: true
    description: Product code.
  net_price:
    type: number
    nullable: true
    description: >-
      Net sale price (used if use_gross_price is false, otherwise it's competed
      automatically).
  gross_price:
    type: number
    nullable: true
    description: >-
      Gross sale price (used if use_gross_price is false, otherwise it's
      competed automatically).
  use_gross_price:
    type: boolean
    description: Determine which price to use for calculations.
    nullable: true
  default_vat:
    $ref: ./VatType.yaml
    nullable: true
  net_cost:
    type: number
    nullable: true
    description: Net cost of the product (used for received documents).
  measure:
    type: string
    nullable: true
    description: Unit of measure.
  description:
    type: string
    description: Product description.
    nullable: true
  category:
    type: string
    description: Product category.
    nullable: true
  notes:
    type: string
    nullable: true
    description: Extra notes.
  in_stock:
    type: boolean
    description: Determine if the product is in stock.
    nullable: true
  stock_initial:
    type: number
    description: Product initial stock.
    nullable: true
  stock_current:
    type: number
    description: |-
      [Read Only]
      Product current stock.
    readOnly: true
    nullable: true
  average_cost:
    type: number
    description: Product average cost.
    nullable: true
  average_price:
    type: number
    description: Product average price.
    nullable: true
  created_at:
    type: string
    nullable: true
  updated_at:
    type: string
    nullable: true
title: Product
