type: object
title: Product
properties:
  id:
    type: integer
    description: Product id
    nullable: true
  name:
    type: string
    description: Product name
    nullable: true
  code:
    type: string
    nullable: true
    description: Product code
  net_price:
    type: number
    nullable: true
    description: Product net price
  gross_price:
    type: number
    nullable: true
    description: Product gross price
  use_gross_price:
    type: boolean
    description: Product uses gross prices
    nullable: true
  default_vat:
    $ref: ./VatType.yaml
  net_cost:
    type: number
    nullable: true
    description: Product net cost
  measure:
    type: string
    nullable: true
    description: Product measure
  description:
    type: string
    description: Product description
    nullable: true
  category:
    type: string
    description: Product category
    nullable: true
  notes:
    type: string
    nullable: true
    description: Product extra notes
  in_stock:
    type: boolean
    description: Product has stock
    nullable: true
  stock_initial:
    type: number
    description: Product initial stock
    nullable: true
  stock_current:
    type: number
    description: |-
      [Read Only]
      Product current stock
    nullable: true
    readOnly: true
  average_cost:
    type: number
    description: Product average cost
    nullable: true
  average_price:
    type: number
    description: Product average price
    nullable: true
  created_at:
    type: string
    nullable: true
    description: Product creation date
  updated_at:
    type: string
    nullable: true
    description: Product last update date
