openapi: 3.0.3
info:
  contact:
    email: info@fattureincloud.it
    name: Fatture in Cloud
    url: https://www.fattureincloud.it
  description: "Connect your software with Fatture in Cloud, the invoicing platform\
    \ chosen by more than 500.000 businesses in Italy. \n\nThe Fatture in Cloud API\
    \ is based on REST, and makes possible to interact with the user related data\
    \ prior authorization via OAuth2 protocol."
  license:
    name: MIT
    url: https://github.com/fattureincloud/openapi-fattureincloud/blob/master/LICENSE
  title: Fatture in Cloud API v2 - API Reference
  version: 2.1.5
servers:
- url: https://api-v2.fattureincloud.it
security:
- OAuth2AuthenticationCodeFlow: []
tags:
- name: Archive
- name: Cashbook
- name: Clients
- name: Companies
- name: Info
- name: Issued Documents
- name: Issued e-invoices
- name: Products
- name: PriceLists
- name: Receipts
- name: Received Documents
- name: Suppliers
- name: Taxes
- name: User
paths:
  /user/info:
    get:
      description: Gets the current user's info.
      operationId: getUserInfo
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get User Info
      tags:
      - User
  /user/companies:
    get:
      description: Lists the companies controlled by the current user.
      operationId: listUserCompanies
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List User Companies
      tags:
      - User
  /c/{company_id}/company/info:
    get:
      description: Gets the company detailed info.
      operationId: getCompanyInfo
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Company Info
      tags:
      - Companies
  /c/{company_id}/company/plan_usage:
    get:
      description: Gets the company limits usage.
      operationId: getCompanyPlanUsage
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Company Plan Usage
      tags:
      - Companies
  /c/{company_id}/entities/clients:
    get:
      description: Lists the clients.
      operationId: listClients
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:r
      summary: List Clients
      tags:
      - Clients
    post:
      description: Creates a new client.
      operationId: createClient
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:a
      summary: Create Client
      tags:
      - Clients
  /c/{company_id}/entities/clients/{client_id}:
    delete:
      description: Deletes the specified client.
      operationId: deleteClient
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:a
      summary: Delete Client
      tags:
      - Clients
    get:
      description: Gets the specified client.
      operationId: getClient
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:r
      summary: Get Client
      tags:
      - Clients
    put:
      description: Modifies the specified client.
      operationId: modifyClient
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:a
      summary: Modify Client
      tags:
      - Clients
  /c/{company_id}/entities/clients/info:
    get:
      description: Retrieves the information useful while creating a new Client.
      operationId: getClientInfo
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.clients:r
      summary: Get Client info
      tags:
      - Clients
  /c/{company_id}/entities/suppliers:
    get:
      description: Lists the suppliers.
      operationId: listSuppliers
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.suppliers:r
      summary: List Suppliers
      tags:
      - Suppliers
    post:
      description: Creates a new supplier.
      operationId: createSupplier
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.suppliers:a
      summary: Create Supplier
      tags:
      - Suppliers
  /c/{company_id}/entities/suppliers/{supplier_id}:
    delete:
      description: Deletes the specified supplier.
      operationId: deleteSupplier
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.suppliers:a
      summary: Delete Supplier
      tags:
      - Suppliers
    get:
      description: Gets the specified supplier.
      operationId: getSupplier
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.suppliers:r
      summary: Get Supplier
      tags:
      - Suppliers
    put:
      description: Modifies the specified supplier.
      operationId: modifySupplier
      security:
      - OAuth2AuthenticationCodeFlow:
        - entity.suppliers:a
      summary: Modify Supplier
      tags:
      - Suppliers
  /c/{company_id}/products:
    get:
      description: Lists the products.
      operationId: listProducts
      security:
      - OAuth2AuthenticationCodeFlow:
        - products:r
      summary: List Products
      tags:
      - Products
    post:
      description: Creates a new product.
      operationId: createProduct
      security:
      - OAuth2AuthenticationCodeFlow:
        - products:a
      summary: Create Product
      tags:
      - Products
  /c/{company_id}/products/{product_id}:
    delete:
      description: Deletes the specified product.
      operationId: deleteProduct
      security:
      - OAuth2AuthenticationCodeFlow:
        - products:a
      summary: Delete Product
      tags:
      - Products
    get:
      description: Gets the specified product.
      operationId: getProduct
      security:
      - OAuth2AuthenticationCodeFlow:
        - products:r
      summary: Get Product
      tags:
      - Products
    put:
      description: Modifies the specified product.
      operationId: modifyProduct
      security:
      - OAuth2AuthenticationCodeFlow:
        - products:a
      summary: Modify Product
      tags:
      - Products
  /c/{company_id}/issued_documents:
    get:
      description: Lists the issued documents.
      operationId: listIssuedDocuments
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
        - issued_documents.delivery_notes:r
      summary: List Issued Documents
      tags:
      - Issued Documents
    post:
      description: Creates a new document.
      operationId: createIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:a
        - issued_documents.credit_notes:a
        - issued_documents.receipts:a
        - issued_documents.orders:a
        - issued_documents.quotes:a
        - issued_documents.proformas:a
        - issued_documents.delivery_notes:a
      summary: Create Issued Document
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/{document_id}:
    delete:
      description: Deletes the specified document.
      operationId: deleteIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:a
        - issued_documents.credit_notes:a
        - issued_documents.receipts:a
        - issued_documents.orders:a
        - issued_documents.quotes:a
        - issued_documents.proformas:a
        - issued_documents.delivery_notes:a
      summary: Delete Issued Document
      tags:
      - Issued Documents
    get:
      description: |
        Gets the specified document.
      operationId: getIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
        - issued_documents.delivery_notes:r
      summary: Get Issued Document
      tags:
      - Issued Documents
    put:
      description: Modifies the specified document.
      operationId: modifyIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:a
        - issued_documents.credit_notes:a
        - issued_documents.receipts:a
        - issued_documents.orders:a
        - issued_documents.quotes:a
        - issued_documents.proformas:a
        - issued_documents.delivery_notes:a
      summary: Modify Issued Document
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/totals:
    post:
      description: Returns the totals for a new document.
      operationId: getNewIssuedDocumentTotals
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get New Issued Document Totals
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/{document_id}/totals:
    post:
      description: Returns the totals for a specified document.
      operationId: getExistingIssuedDocumentTotals
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Existing Issued Document Totals
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/attachment:
    post:
      description: "Uploads an attachment destined to an issued document. The actual\
        \ association between the document and the attachment must be implemented\
        \ separately, using the returned token."
      operationId: uploadIssuedDocumentAttachment
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Upload Issued Document Attachment
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/{document_id}/attachment:
    delete:
      description: Removes the attachment of the specified document.
      operationId: deleteIssuedDocumentAttachment
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Delete Issued Document Attachment
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/info:
    get:
      description: Retrieves the information useful while creating a new document.
      operationId: getIssuedDocumentPreCreateInfo
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Issued Document Pre-Create Info
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/{document_id}/email:
    get:
      description: Gets the pre-compiled email details.
      operationId: getEmailData
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
        - issued_documents.delivery_notes:r
      summary: Get Email Data
      tags:
      - Issued Documents
    post:
      description: Schedules the sending of a document by email.
      operationId: scheduleEmail
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
        - issued_documents.delivery_notes:r
      summary: Schedule Email
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/{document_id}/e_invoice/send:
    post:
      description: Sends the e-invoice to SDI.
      operationId: sendEInvoice
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Send E-Invoice
      tags:
      - Issued e-invoices
  /c/{company_id}/issued_documents/{document_id}/e_invoice/xml_verify:
    get:
      description: Verifies the e-invoice XML format. Checks if all of the mandatory
        fields are filled and compliant to the right format.
      operationId: verifyEInvoiceXml
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Verify E-Invoice XML
      tags:
      - Issued e-invoices
  /c/{company_id}/issued_documents/{document_id}/e_invoice/xml:
    get:
      description: Downloads the e-invoice in XML format.
      operationId: getEInvoiceXml
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get E-Invoice XML
      tags:
      - Issued e-invoices
  /c/{company_id}/issued_documents/{document_id}/e_invoice/error_reason:
    get:
      description: Get e-invoice rejection reason
      operationId: getEInvoiceRejectionReason
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get E-Invoice Rejection Reason
      tags:
      - Issued e-invoices
  /c/{company_id}/received_documents:
    get:
      description: Lists the received documents.
      operationId: listReceivedDocuments
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:r
        - stock:r
      summary: List Received Documents
      tags:
      - Received Documents
    post:
      description: Creates a new document.
      operationId: createReceivedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Create Received Document
      tags:
      - Received Documents
  /c/{company_id}/received_documents/{document_id}:
    delete:
      description: Deletes the specified document.
      operationId: deleteReceivedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Delete Received Document
      tags:
      - Received Documents
    get:
      description: Gets the specified document.
      operationId: getReceivedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:r
        - stock:r
      summary: Get Received Document
      tags:
      - Received Documents
    put:
      description: Modifies the specified document.
      operationId: modifyReceivedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Modify Received Document
      tags:
      - Received Documents
  /c/{company_id}/received_documents/totals:
    post:
      description: Returns the totals for a new document.
      operationId: getNewReceivedDocumentTotals
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Get New Received Document Totals
      tags:
      - Received Documents
  /c/{company_id}/received_documents/{document_id}/totals:
    post:
      description: Returns the totals for the specified document.
      operationId: getExistingReceivedDocumentTotals
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Get Existing Received Document Totals
      tags:
      - Received Documents
  /c/{company_id}/received_documents/attachment:
    post:
      description: "Uploads an attachment destined to a received document. The actual\
        \ association between the document and the attachment must be implemented\
        \ separately, using the returned token."
      operationId: uploadReceivedDocumentAttachment
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Upload Received Document Attachment
      tags:
      - Received Documents
  /c/{company_id}/received_documents/{document_id}/attachment:
    delete:
      description: Removes the attachment of the specified document.
      operationId: deleteReceivedDocumentAttachment
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:a
        - stock:a
      summary: Delete Received Document Attachment
      tags:
      - Received Documents
  /c/{company_id}/received_documents/info:
    get:
      description: Retrieves the information useful while creating a new document.
      operationId: getReceivedDocumentPreCreateInfo
      security:
      - OAuth2AuthenticationCodeFlow:
        - received_documents:r
      summary: Get Received Document Pre-Create Info
      tags:
      - Received Documents
  /c/{company_id}/receipts:
    get:
      description: Lists the receipts.
      operationId: listReceipts
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:r
      summary: List Receipts
      tags:
      - Receipts
    post:
      description: Creates a new receipt.
      operationId: createReceipt
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:a
      summary: Create Receipt
      tags:
      - Receipts
  /c/{company_id}/receipts/{document_id}:
    delete:
      description: Deletes the specified receipt.
      operationId: deleteReceipt
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:a
      summary: Delete Receipt
      tags:
      - Receipts
    get:
      description: Gets the specified receipt.
      operationId: getReceipt
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:r
      summary: Get Receipt
      tags:
      - Receipts
    put:
      description: Modifies the specified receipt.
      operationId: modifyReceipt
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:a
      summary: Modify Receipt
      tags:
      - Receipts
  /c/{company_id}/receipts/info:
    get:
      description: Retrieves the information useful while creating a new receipt.
      operationId: getReceiptPreCreateInfo
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:r
      summary: Get Receipt Pre-Create Info
      tags:
      - Receipts
  /c/{company_id}/receipts/monthly_totals:
    get:
      description: Returns the monthly totals by year and receipt type.
      operationId: getReceiptsMonthlyTotals
      security:
      - OAuth2AuthenticationCodeFlow:
        - receipts:r
      summary: Get Receipts Monthly Totals
      tags:
      - Receipts
  /c/{company_id}/taxes:
    get:
      description: Lists the F24s.
      operationId: listF24
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:r
      summary: List F24
      tags:
      - Taxes
    post:
      description: Creates a new F24.
      operationId: createF24
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:a
      summary: Create F24
      tags:
      - Taxes
  /c/{company_id}/taxes/{document_id}:
    delete:
      description: Removes the specified F24.
      operationId: deleteF24
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:a
      summary: Delete F24
      tags:
      - Taxes
    get:
      description: Gets the specified F24.
      operationId: getF24
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:r
      summary: Get F24
      tags:
      - Taxes
    put:
      description: Modifies the specified F24.
      operationId: modifyF24
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:a
      summary: Modify F24
      tags:
      - Taxes
  /c/{company_id}/taxes/attachment:
    post:
      description: "Uploads an attachment destined to a F24. The actual association\
        \ between the document and the attachment must be implemented separately,\
        \ using the returned token."
      operationId: uploadF24Attachment
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:a
      summary: Upload F24 Attachment
      tags:
      - Taxes
  /c/{company_id}/taxes/{document_id}/attachment:
    delete:
      description: Removes the attachment of the specified F24.
      operationId: deleteF24Attachment
      security:
      - OAuth2AuthenticationCodeFlow:
        - taxes:a
      summary: Delete F24 Attachment
      tags:
      - Taxes
  /c/{company_id}/archive:
    get:
      description: Lists the archive documents.
      operationId: listArchiveDocuments
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:r
      summary: List Archive Documents
      tags:
      - Archive
    post:
      description: Creates a new archive document.
      operationId: createArchiveDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:a
      summary: Create Archive Document
      tags:
      - Archive
  /c/{company_id}/archive/{document_id}:
    delete:
      description: Deletes the specified archive document.
      operationId: deleteArchiveDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:a
      summary: Delete Archive Document
      tags:
      - Archive
    get:
      description: Gets the specified archive document.
      operationId: getArchiveDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:r
      summary: Get Archive Document
      tags:
      - Archive
    put:
      description: Modifies the specified archive document.
      operationId: modifyArchiveDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:a
      summary: Modify Archive Document
      tags:
      - Archive
  /c/{company_id}/archive/attachment:
    post:
      description: "Uploads an attachment destined to an archive document. The actual\
        \ association between the document and the attachment must be implemented\
        \ separately, using the returned token."
      operationId: uploadArchiveDocumentAttachment
      security:
      - OAuth2AuthenticationCodeFlow:
        - archive:a
      summary: Upload Archive Document Attachment
      tags:
      - Archive
  /c/{company_id}/cashbook:
    get:
      description: Lists the cashbook entries.
      operationId: listCashbookEntries
      security:
      - OAuth2AuthenticationCodeFlow:
        - cashbook:r
      summary: List Cashbook Entries
      tags:
      - Cashbook
    post:
      description: Creates a new cashbook entry.
      operationId: createCashbookEntry
      security:
      - OAuth2AuthenticationCodeFlow:
        - cashbook:a
      summary: Create Cashbook Entry
      tags:
      - Cashbook
  /c/{company_id}/cashbook/{document_id}:
    delete:
      description: Deletes the specified cashbook entry.
      operationId: deleteCashbookEntry
      security:
      - OAuth2AuthenticationCodeFlow:
        - cashbook:a
      summary: Delete Cashbook Entry
      tags:
      - Cashbook
    get:
      description: Gets the specified cashbook entry.
      operationId: getCashbookEntry
      security:
      - OAuth2AuthenticationCodeFlow:
        - cashbook:r
      summary: Get Cashbook Entry
      tags:
      - Cashbook
    put:
      description: Modifies the specified cashbook entry.
      operationId: modifyCashbookEntry
      security:
      - OAuth2AuthenticationCodeFlow:
        - cashbook:a
      summary: Modify Cashbook Entry
      tags:
      - Cashbook
  /info/countries:
    get:
      description: Lists the supported countries.
      operationId: listCountries
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Countries
      tags:
      - Info
  /info/detailed_countries:
    get:
      description: Lists the supported countries.
      operationId: listDetailedCountries
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Detailed Countries
      tags:
      - Info
  /info/cities:
    get:
      description: Lists the Italian cities.
      operationId: listCities
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Cities
      tags:
      - Info
  /info/languages:
    get:
      description: Lists the supported languages.
      operationId: listLanguages
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Languages
      tags:
      - Info
  /info/templates:
    get:
      description: Lists the available templates.
      operationId: listTemplates
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Templates
      tags:
      - Info
  /info/currencies:
    get:
      description: Lists the supported currencies.
      operationId: listCurrencies
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Currencies
      tags:
      - Info
  /info/measures:
    get:
      description: Lists the units of measure.
      operationId: listUnitsOfMeasure
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Units of Measure
      tags:
      - Info
  /info/dn_causals:
    get:
      description: Lists the delivery note default causals.
      operationId: listDeliveryNotesDefaultCausals
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Delivery Notes Default Causals
      tags:
      - Info
  /c/{company_id}/info/vat_types:
    get:
      description: Lists the available vat types.
      operationId: listVatTypes
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:r
      summary: List Vat Types
      tags:
      - Info
  /c/{company_id}/info/payment_methods:
    get:
      description: Lists the available payment methods.
      operationId: listPaymentMethods
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Payment Methods
      tags:
      - Info
  /c/{company_id}/info/payment_accounts:
    get:
      description: Lists the available payment accounts.
      operationId: listPaymentAccounts
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Payment Accounts
      tags:
      - Info
  /c/{company_id}/info/revenue_centers:
    get:
      description: Lists the revenue centers.
      operationId: listRevenueCenters
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Revenue Centers
      tags:
      - Info
  /c/{company_id}/info/cost_centers:
    get:
      description: Lists the cost centers.
      operationId: listCostCenters
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Cost Centers
      tags:
      - Info
  /c/{company_id}/info/product_categories:
    get:
      description: Lists the product categories.
      operationId: listProductCategories
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Product Categories
      tags:
      - Info
  /c/{company_id}/info/received_document_categories:
    get:
      description: Lists the received document categories.
      operationId: listReceivedDocumentCategories
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Received Document Categories
      tags:
      - Info
  /c/{company_id}/info/archive_categories:
    get:
      description: Lists the archive categories.
      operationId: listArchiveCategories
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Archive Categories
      tags:
      - Info
  /c/{company_id}/settings/payment_methods:
    post:
      description: Creates a new payment method.
      operationId: createPaymentMethod
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Create Payment Method
      tags:
      - Settings
  /c/{company_id}/settings/payment_methods/{payment_method_id}:
    delete:
      description: Deletes the specified payment method.
      operationId: deletePaymentMethod
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Delete Payment Method
      tags:
      - Settings
    get:
      description: Gets the specified payment method.
      operationId: getPaymentMethod
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Payment Method
      tags:
      - Settings
    put:
      description: Modifies the specified payment method.
      operationId: modifyPaymentMethod
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Modify Payment Method
      tags:
      - Settings
  /c/{company_id}/settings/payment_accounts:
    post:
      description: Creates a new payment account.
      operationId: createPaymentAccount
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Create Payment Account
      tags:
      - Settings
  /c/{company_id}/settings/tax_profile:
    get:
      description: Gets the Tax Profile
      operationId: getTaxProfile
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:r
      summary: Get Tax Profile
      tags:
      - Settings
  /c/{company_id}/settings/payment_accounts/{payment_account_id}:
    delete:
      description: Deletes the specified payment account.
      operationId: deletePaymentAccount
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Delete Payment Account
      tags:
      - Settings
    get:
      description: Gets the specified payment account.
      operationId: getPaymentAccount
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Payment Account
      tags:
      - Settings
    put:
      description: Modifies the specified payment account.
      operationId: modifyPaymentAccount
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Modify Payment Account
      tags:
      - Settings
  /c/{company_id}/settings/vat_types:
    post:
      description: Creates a vat type.
      operationId: createVatType
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Create Vat Type
      tags:
      - Settings
  /c/{company_id}/settings/vat_types/{vat_type_id}:
    delete:
      description: Deletes the specified vat type.
      operationId: deleteVatType
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Delete Vat Type
      tags:
      - Settings
    get:
      description: Gets the specified vat type.
      operationId: getVatType
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Vat Type
      tags:
      - Settings
    put:
      description: Modifies the specified vat type.
      operationId: modifyVatType
      security:
      - OAuth2AuthenticationCodeFlow:
        - settings:a
      summary: Modify Vat Type
      tags:
      - Settings
  /c/{company_id}/issued_documents/transform:
    get:
      description: Transforms the document.
      operationId: transformIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Transform Issued Document
      tags:
      - Issued Documents
  /c/{company_id}/issued_documents/join:
    get:
      description: Joins issued documents.
      operationId: joinIssuedDocuments
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Join Issued Documents
      tags:
      - Issued Documents
  /c/{company_id}/emails:
    get:
      description: List Emails.
      operationId: listEmails
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Emails
      tags:
      - Emails
  /c/{company_id}/subscriptions:
    get:
      description: List active webhooks subscriptions.
      operationId: listWebhooksSubscriptions
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: List Webhooks Subscriptions
      tags:
      - Webhooks
    post:
      description: Register some webhooks Subscriptions.
      operationId: CreateWebhooksSubscription
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Create a Webhook Subscription
      tags:
      - Webhooks
  /c/{company_id}/subscriptions/{subscription_id}:
    delete:
      description: Delete a webhooks subscription.
      operationId: deleteWebhooksSubscription
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Delete Webhooks Subscription
      tags:
      - Webhooks
    get:
      description: Get a webhooks subscription.
      operationId: getWebhooksSubscription
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Webhooks Subscription
      tags:
      - Webhooks
    put:
      description: Edit a webhooks subscription.
      operationId: modifyWebhooksSubscription
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Modify Webhooks Subscription
      tags:
      - Webhooks
  /c/{company_id}/subscriptions/{subscription_id}/verify:
    post:
      description: Verify a webhook subscription.
      operationId: verifyWebhooksSubscription
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Verify Webhooks Subscription
      tags:
      - Webhooks
  /c/{company_id}/bin/issued_documents:
    get:
      description: Get bin issued documents list
      operationId: ListBinIssuedDocuments
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
      summary: Get Bin Issued Documents List
      tags:
      - Issued Documents
  /c/{company_id}/bin/issued_documents/{document_id}:
    delete:
      description: Delete Bin Issued Document
      operationId: DeleteBinIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Delete Bin Issued Document
      tags:
      - Issued Documents
    get:
      description: Get bin issued documents detail
      operationId: GetBinIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow:
        - issued_documents.invoices:r
        - issued_documents.credit_notes:r
        - issued_documents.receipts:r
        - issued_documents.orders:r
        - issued_documents.quotes:r
        - issued_documents.proformas:r
      summary: Get Bin Issued Documents List
      tags:
      - Issued Documents
  /c/{company_id}/bin/issued_documents/{document_id}/recover:
    post:
      description: Recover Issued Document From The Bin
      operationId: RecoverBinIssuedDocument
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Recover Issued Document From The Bin
      tags:
      - Issued Documents
  /c/{company_id}/bin/received_documents:
    get:
      description: Get bin Received documents list
      operationId: ListBinReceivedDocuments
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Bin Received Documents List
      tags:
      - Received Documents
  /c/{company_id}/bin/received_documents/{document_id}:
    delete:
      description: Delete Bin Received Document
      operationId: DeleteBinReceivedDocument
      summary: Delete Bin Received Document
      tags:
      - Received Documents
    get:
      description: Get bin issued documents detail
      operationId: GetBinReceivedDocument
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get Bin Received Documents List
      tags:
      - Received Documents
  /c/{company_id}/bin/received_documents/{document_id}/recover:
    post:
      description: Recover Received Document From The Bin
      operationId: RecoverBinReceivedDocument
      summary: Recover Received Document From The Bin
      tags:
      - Received Documents
  /c/{company_id}/price_lists:
    get:
      description: Retrieves all price lists of the company
      operationId: getPriceLists
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get PriceLists
      tags:
      - PriceLists
  /c/{company_id}/price_lists/{price_list_id}/items:
    get:
      description: Retrieves all the Items of a PriceList
      operationId: getPriceListItems
      security:
      - OAuth2AuthenticationCodeFlow: []
      summary: Get PriceList Items List
      tags:
      - PriceLists
components:
  securitySchemes:
    OAuth2AuthenticationCodeFlow:
      flows:
        authorizationCode:
          authorizationUrl: https://api-v2.fattureincloud.it/oauth/authorize
          refreshUrl: https://api-v2.fattureincloud.it/oauth/token
          scopes:
            entity.clients:r: Read permission to the Clients registry
            entity.clients:a: Write permission to the Clients registry
            entity.suppliers:r: Read permission to the Suppliers registry
            entity.suppliers:a: Write permission to the Suppliers registry
            products:r: Read permission to the Products
            products:a: Write permission to the Products
            issued_documents.invoices:r: Read permission to the issued Invoices
            issued_documents.credit_notes:r: Read permission to the issued Credit
              Notes
            issued_documents.receipts:r: Read permission to the issued Receipts
            issued_documents.orders:r: Read permission to the issued Orders
            issued_documents.quotes:r: Read permission to the issued Quotes
            issued_documents.proformas:r: Read permission to the issued Proformas
            issued_documents.delivery_notes:r: Read permission to the issued Delivery
              Notes
            issued_documents.work_reports:r: Read permission to the issued Work Reports
            issued_documents.supplier_orders:r: Read permission to the issued Supplier
              Orders
            issued_documents.self_invoices:r: Read permission to the issued Self Invoices
            issued_documents.invoices:a: Write permission to the issued Invoices
            issued_documents.credit_notes:a: Write permission to the issued Credit
              Notes
            issued_documents.receipts:a: Write permission to the issued issued Receipts
            issued_documents.orders:a: Write permission to the issued Orders
            issued_documents.quotes:a: Write permission to the issued Quotes
            issued_documents.proformas:a: Write permission to the issued Proformas
            issued_documents.delivery_notes:a: Write permission to the issued Delivery
              Notes
            issued_documents.work_reports:a: Write permission to the issued Work Reports
            issued_documents.supplier_orders:a: Write permission to the issued Supplier
              Orders
            issued_documents.self_invoices:a: Write permission to the issued Self
              Invoices
            received_documents:r: Read permission to the Received Documents
            received_documents:a: Write permission to the Received Documents
            stock:r: Read permission to the Stock movements
            stock:a: Write permission to the Stock movements
            receipts:r: Read permission to the Receipts
            receipts:a: Write permission to the Receipts
            calendar:r: Read permission to the Calendar
            calendar:a: Write permission to the Calendar
            taxes:r: Read permission to the Taxes
            taxes:a: Write permission to the Taxes
            archive:r: Read permission to the Archive Documents
            archive:a: Read permission to the Archive Documents
            emails:r: Read permission to the Emails
            cashbook:r: Read permission to the Cashbook
            cashbook:a: Write permission to the Cashbook
            settings:r: Read permission to the Settings
            settings:a: Write permission to the Settings
            situation:r: Read permission to the company Situation
          tokenUrl: https://api-v2.fattureincloud.it/oauth/token
      type: oauth2
      x-receive-token-in: request-body

