/*
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.fattureincloud.sdk.api;

import it.fattureincloud.sdk.ApiException;
import it.fattureincloud.sdk.model.GetCompanyInfoResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompaniesApi
 */
@Ignore
public class CompaniesApiTest {

    private final CompaniesApi api = new CompaniesApi();

    
    /**
     * Get Company Info
     *
     * Gets the company detailed info.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyInfoTest() throws ApiException {
        Integer companyId = null;
                GetCompanyInfoResponse response = api.getCompanyInfo(companyId);
        // TODO: test validations
    }
    
}
