name: Openapi Spec Enrichment
on:
  repository_dispatch:
    types: [enrich-spec]

jobs:
  enrich-openapi:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}

      - id: init-git
        name: Init GIT
        run: |
          git config --global user.email "info@fattureincloud.it"
          git config --global user.name "fattureincloud-bot"
          
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v4

      - id: setup-libraries
        name: Install libraries
        run: |
          npm install -g yarn
          yarn global add @apidevtools/swagger-cli @openapitools/openapi-generator-cli swagger-merger
          cd ./scripts/
          yarn

      - id: enrich-spec
        name: Enrich OpenAPI Spec
        run: |
          echo "Resolving OpenAPI Specification to a single file..."
          swagger-merger -i ./openapi.yaml -o ./openapi-enriched.yaml

          echo "Enriching OpenAPI Specification..."
          node ./scripts/enrich.js ./details.yaml ./openapi-enriched.yaml

      - id: validate-enriched-spec
        name: Validate enriched specification
        run: |
          swagger-cli validate openapi-enriched.yaml
          openapi-generator-cli validate -i ./openapi-enriched.yaml

      - id: get-timestamp
        name: Get Current Timestamp
        run: |
          DATE=$(date '+%Y%m%d')
          echo "date_ts=$DATE" >> $GITHUB_ENV
          
      - id: create-pr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: "."
          branch: "enriched-spec-${{ env.date_ts }}"
          token: "${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}"
          delete-branch: true
          base: develop
          commit-message: "chore: openapi spec enrichment"
          title: "OpenAPI spec enrichment"
          body: ""