name: Generate TypeScript SDK
on:
  repository_dispatch:
    types: [generate-typescript-axios]

jobs:
  generate-typescript-sdk:
    runs-on: ubuntu-latest
    env:
      GIT_REPO_ID: fattureincloud-ts-sdk
      GIT_USER_ID: fattureincloud
    steps: 

      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}

      - id: checkout-ts
        name: Checkout TypeScript repo
        env:
          GIT_REPO_PATH: '${{ env.GIT_USER_ID }}/${{ env.GIT_REPO_ID }}'
        uses: actions/checkout@v2
        with:
          path: ./generated/typescript-axios
          ref: master
          repository: ${{ env.GIT_REPO_PATH }}
          token: ${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}

      - id: init-git
        name: Init GIT
        run: |
          git config --global user.email "info@fattureincloud.it"
          git config --global user.name "fattureincloud-bot"
          
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v2

      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - id: setup-libraries
        name: Install libraries
        run: |
          npm install -g yarn
          yarn global add @apidevtools/swagger-cli @openapitools/openapi-generator-cli standard-version
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt update
          sudo apt install yq -y
          cd ./scripts/
          yarn
          cd ../generated/typescript-axios/scripts
          yarn

      - id: bump-typescript-sdk-version
        name: Bump C# SDK
        env:
          OPENAPI_VERSION: ${{ github.event.client_payload.version }}
        run: |

          echo "openapi_version=$OPENAPI_VERSION"

          BUMP_TYPE=$(node ./scripts/sdk-version-checker.js ./generated/typescript-axios/sdk-version.yaml $OPENAPI_VERSION)

          cd ./generated/typescript-axios

          if [ "$BUMP_TYPE" == "patch" ];then
            echo 'Bumping the SDK patch version...'
            standard-version --skip.tag --skip.changelog --skip.commit --release-as patch
          elif [ "$BUMP_TYPE" == "openapi" ];then
            echo 'Using the openapi version...'
            standard-version --skip.tag --skip.changelog --skip.commit --release-as $OPENAPI_VERSION
          else
            echo "Something bad happened - impossible to bump C# SDK version. value=$BUMP_TYPE"
          fi

          SDK_VERSION=$(yq e '.info.version' ./sdk-version.yaml)

          echo "sdk_version=$SDK_VERSION" >> $GITHUB_ENV
          echo "openapi_version=$OPENAPI_VERSION" >> $GITHUB_ENV

      - id: move-custom-files-to-backup
        name: Move custom files to backup
        run: |
          mkdir -p ./backup/typescript-axios/src/filter
          mkdir -p ./backup/typescript-axios/src/oauth2
          mv ./generated/typescript-axios/src/filter ./backup/typescript-axios/src/
          mv ./generated/typescript-axios/src/oauth2 ./backup/typescript-axios/src/

      - id: delete-old-files
        name: Delete old files
        run: |
          rm -rf ./generated/typescript-axios/src
          rm -rf ./generated/typescript-axios/docs
          rm -rf ./generated/typescript-axios-docs

      - id: generate-typescript-axios
        name: Generate TypeScript SDK
        env:
          PACKAGE_NAME: "@fattureincloud/fattureincloud-ts-sdk"
          APP_NAME: "FattureInCloud"
        run: |
          SDK_VERSION=${{ env.sdk_version }}
          echo "${{ env.sdk_version }}"
          
          RELEASE_NOTE="\"bumping version to $SDK_VERSION\""

          USER_AGENT="$APP_NAME/${{ env.sdk_version }}/TypeScript-SDK"
          
          openapi-generator-cli generate -i ./openapi.yaml -g typescript-axios -o generated/typescript-axios/ -t ./templates/openapi-generator/typescript-axios --additional-properties=npmName=${PACKAGE_NAME},npmVersion=${SDK_VERSION},supportsES6=true,withNodeImports=true,withSeparateModelsAndApi=true,apiPackage=src/api,modelPackage=src/models,withInterfaces=true --git-repo-id=${GIT_REPO_ID} --git-user-id=${GIT_USER_ID} --release-note=${RELEASE_NOTE} --http-user-agent=${USER_AGENT}

      - id: generate-typescript-axios-docs
        name: Generate Docs
        run: openapi-generator-cli generate -i ./openapi.yaml -g javascript -o generated/typescript-axios-docs/  -t ./templates/openapi-generator/typescript-axios-docs

      - id: move-docs
        name: Moving Docs To The Right Folder
        run: mv ./generated/typescript-axios-docs/docs ./generated/typescript-axios 

      - id: move-custom-files-to-repo
        name: Move custom files to repo
        run: |
          mv ./backup/typescript-axios/src/filter ./generated/typescript-axios/src/
          mv ./backup/typescript-axios/src/oauth2 ./generated/typescript-axios/src/

      - id: generate-additional-files
        name: Generate Additional files
        run: |
          node ./scripts/generate-scopes.js typescript-axios

      - id: lint-code
        name: Lint Code Base
        run: |
          cd ./generated/typescript-axios
          npm install
          npx eslint --fix ./

      - id: create-pr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: ./generated/typescript-axios
          branch: "devel-${{ env.sdk_version }}"
          token: "${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}"
          delete-branch: true
          base: master
          commit-message: "chore: bumping version to ${{ env.sdk_version }}"
          title: "Updating SDK to ${{ env.sdk_version }}"
          body: "New SDK verson ${{ env.sdk_version }} generated by Github Action from OpenAPI Spec ${{ env.openapi_version }}"   