name: Generate PHP SDK
on:
  repository_dispatch:
    types: [generate-php]
    
jobs:
  generate-php-sdk:
    runs-on: ubuntu-latest
    env:
      GIT_REPO_ID: fattureincloud-php-sdk
      GIT_USER_ID: fattureincloud
    steps: 

      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}
      
      - id: checkout-php
        name: Checkout PHP repo
        env:
          GIT_REPO_PATH: '${{ env.GIT_USER_ID }}/${{ env.GIT_REPO_ID }}'
        uses: actions/checkout@v2
        with:
          path: ./generated/php
          ref: master
          repository: ${{ env.GIT_REPO_PATH }}
          token: ${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}

      - id: init-git
        name: Init GIT
        run: |
          git config --global user.email "info@fattureincloud.it"
          git config --global user.name "fattureincloud-bot"

      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v2

      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - id: setup-libraries
        name: Install libraries
        run: |
          npm install -g yarn
          yarn global add @apidevtools/swagger-cli @openapitools/openapi-generator-cli standard-version
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt update
          sudo apt install yq -y
          cd ./scripts/
          yarn
          cd ../generated/php/scripts
          yarn

      - id: bump-php-sdk-version
        name: Bump PHP SDK
        env:
          OPENAPI_VERSION: ${{ github.event.client_payload.version }}
        run: |

          echo "openapi_version=$OPENAPI_VERSION"

          BUMP_TYPE=$(node ./scripts/sdk-version-checker.js ./generated/php/sdk-version.yaml $OPENAPI_VERSION)

          cd ./generated/php

          if [ "$BUMP_TYPE" == "patch" ];then
            echo 'Bumping the SDK patch version...'
            standard-version --release-as patch
          elif [ "$BUMP_TYPE" == "openapi" ];then
            echo 'Using the openapi version...'
            standard-version --release-as $OPENAPI_VERSION
          else
            echo "Something bad happened - impossible to bump PHP SDK version. value=$BUMP_TYPE"
          fi

          SDK_VERSION=$(yq e '.info.version' ./sdk-version.yaml)


          echo "sdk_version=$SDK_VERSION" >> $GITHUB_ENV
          echo "openapi_version=$OPENAPI_VERSION" >> $GITHUB_ENV

      - id: generate-php-sdk
        name: Generate PHP SDK
        env:
          PACKAGE_NAME: "\"FattureInCloud PHP SDK\""
          INVOKER_PACKAGE: FattureInCloud
          AUTHOR_NAME: "\"Fatture in Cloud API Team\""
          HOMEPAGE_URL: https://www.fattureincloud.it
        run: |
          SDK_VERSION=${{ env.sdk_version }}
          echo "${{ env.sdk_version }}"
          RELEASE_NOTE="\"bumping version to $SDK_VERSION\""

          USER_AGENT="$INVOKER_PACKAGE/${{ env.sdk_version }}/PHP-SDK"

          openapi-generator-cli generate -i ./openapi.yaml -g php -o ./generated/php/ -t ./templates/php --package-name=${PACKAGE_NAME} --invoker-package=${INVOKER_PACKAGE} --git-repo-id=${GIT_REPO_ID} --git-user-id=${GIT_USER_ID} --release-note=${RELEASE_NOTE} --http-user-agent=${USER_AGENT}

          node ./scripts/postprocess-php.js clean './generated/php/lib/' './generated/php/test/'
          node ./scripts/postprocess-php.js backport './generated/php/composer.json'
          node ./scripts/postprocess-php.js license MIT './generated/php/composer.json'
          node ./scripts/postprocess-php.js homepage $HOMEPAGE_URL './generated/php/composer.json'
          node ./scripts/postprocess-php.js authors 0 $AUTHOR_NAME $HOMEPAGE_URL './generated/php/composer.json'

      - id: create-pr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: ./generated/php
          branch: "devel-${{ env.sdk_version }}"
          token: "${{ secrets.FATTUREINCLOUD_BOT_TOKEN }}"
          delete-branch: true
          base: master
          commit-message:  "chore: bumping version to ${{ env.sdk_version }}"
          title: "Updating SDK to ${{ env.sdk_version }}"
          body: "New SDK verson ${{ env.sdk_version }} generated by Github Action from OpenAPI Spec ${{ env.openapi_version }}"
